---

- name: centos | close spacewalk client services
  include_role:
    name: services/firewalld/tasks
  vars:
    name: spacewalk client uninstall
    services:
    - name: spacewalk client
      service: ssh
      state: enabled
    ports:
    - name: spacewalk client
      port: 5222/tcp
      state: disabled
