---

- name: centos | open docker metrics ports
  include_role:
    name: services/firewalld/tasks
  vars:
    name: docker
    ports:
    - name: docker node-exporter
      port: 9100/tcp
    - name: docker cadvisor
      port: 9080/tcp
