---

- name: launch node-exporter container
  become: true
  docker_container:
    name: node-exporter
    image: prom/node-exporter:latest
    restart_policy: unless-stopped
    command: --path.rootfs=/hostfs
    hostname: "{{ inventory_hostname }}"
    ports:
    - 9100:9100
    volumes:
    - /:/hostfs

- name: launch cadvisor container
  become: true
  docker_container:
    name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    restart_policy: unless-stopped
    hostname: "{{ inventory_hostname }}"
    ports:
    - 9080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:ro
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    - /dev/disk/:/dev/disk:ro
  when: not is_rpi

- name: launch cadvisor container
  become: true
  docker_container:
    name: cadvisor
    image: gcr.io/cadvisor/cadvisor-arm:v0.46.0
    restart_policy: unless-stopped
    hostname: "{{ inventory_hostname }}"
    ports:
    - 9080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:ro
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    - /dev/disk/:/dev/disk:ro
  when: is_rpi

- name: centos | open firewalld ports
  import_tasks: firewalld.yaml
  when: is_centos
