---

- name: tmm | set facts
  set_fact:
    install_path: "/opt/tinymediamanager-{{ global.version.tmm }}"

- name: tmm | create install dir
  become: yes
  file:
    path: "{{ install_path }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory

- name: tmm | download and untar
  become: yes
  unarchive:
    remote_src: yes
    src: "https://release.tinymediamanager.org/v{{ global.version.tmm_major }}/dist/tmm_{{ global.version.tmm }}_linux.tar.gz"
    dest: "{{ install_path }}"

- name: tmm | create shortcut
  copy:
    force: yes
    dest: ~/.local/share/applications/tinyMediaManager.desktop
    content: |
      [Desktop Entry]
      Type=Application
      Terminal=false
      Name=tinyMediaManager
      Icon={{ install_path }}/tmm.png
      Exec={{ install_path }}/tinyMediaManager.sh
