---

- name: insomnia | check if plugin exists
  stat:
    path: "{{ plugin_path }}/{{ item }}"
  register: plugin

- name: insomnia | install npm pkg
  shell: "source {{ ansible_env['HOME'] }}/.zshrc && npm install --prefix /tmp {{ item }}"
  args:
    executable: /bin/bash
  when: plugin.stat.exists == false

- name: insomnia | move pkg to plugin dir
  command: "mv /tmp/node_modules/{{ item }} {{ plugin_path }}/{{ item }}"
  when: plugin.stat.exists == false
