---

- name: install pip
  apt:
    name: python3-pip
    state: present

- name: install influxdb pip
  pip:
    name: influxdb

- name: create influxdb dirs
  file:
    path: "/mnt/hdd/influxdb"
    state: directory
    owner: "influxdb"
    group: "influxdb"
    mode: "0755"

- name: retrieve types db
  get_url:
    url: https://raw.githubusercontent.com/collectd/collectd/master/src/types.db
    dest: /mnt/hdd/influxdb/types.db
    mode: 0755

- name: configure influxdb settings
  blockinfile:
    insertafter: "{{ item.after }}"
    dest: /etc/influxdb/influxdb.conf
    marker: "# {mark} {{ item.mark }} ANSIBLE MANAGED BLOCK #"
    block: "{{ item.block }}"
  with_items:
  - after: '^\[http\]$'
    mark: "http"
    block: |
      enabled = true
      bind-address = ":8086"
  - after: '^\[\[collectd\]\]$'
    mark: "collectd"
    block: |
      enabled = true
      bind-address = ":{{ config_influxdb['port'] }}"
      database = "{{ config_influxdb_collectd['db'] }}"
      typesdb = "/mnt/hdd/influxdb/types.db"

- name: configure influxdb directories
  lineinfile:
    dest: /etc/influxdb/influxdb.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
  - regexp: dir = .*/meta"
    line: dir = "/mnt/hdd/influxdb/meta"
  - regexp: dir = .*/data"
    line: dir = "/mnt/hdd/influxdb/data"
  - regexp: wal-dir = .*/wal"
    line: wal-dir = "/mnt/hdd/influxdb/wal"
  notify: restart influxdb

- name: create collectd database
  influxdb_database:
    hostname: "{{ config_influxdb_collectd['host'] }}"
    database_name: "{{ config_influxdb_collectd['db'] }}"

- name: create collectd writers
  influxdb_user:
    user_name: "{{ config_influxdb_collectd['writer']['user'] }}"
    user_password: "{{ config_influxdb_collectd['writer']['pass'] }}"
    grants:
    - database: "{{ config_influxdb_collectd['db'] }}"
      privilege: "WRITE"

- name: create collectd reader
  influxdb_user:
    user_name: "{{ config_influxdb_collectd['reader']['user'] }}"
    user_password: "{{ config_influxdb_collectd['reader']['pass'] }}"
    grants:
    - database: "{{ config_influxdb_collectd['db'] }}"
      privilege: "READ"

- name: create pfsense database
  influxdb_database:
    hostname: "{{ config_influxdb_pfsense['host'] }}"
    database_name: "{{ config_influxdb_pfsense['db'] }}"

- name: create pfsense writer
  influxdb_user:
    user_name: "{{ config_influxdb_pfsense['writer']['user'] }}"
    user_password: "{{ config_influxdb_pfsense['writer']['pass'] }}"
    grants:
    - database: "{{ config_influxdb_pfsense['db'] }}"
      privilege: "WRITE"

- name: create pfsense reader
  influxdb_user:
    user_name: "{{ config_influxdb_pfsense['reader']['user'] }}"
    user_password: "{{ config_influxdb_pfsense['reader']['pass'] }}"
    grants:
    - database: "{{ config_influxdb_pfsense['db'] }}"
      privilege: "READ"
