---

- name: install pip
  yum:
    name:
    - python3-pip
    - python2-pip
    state: present

- name: install influxdb pip
  pip:
    name: influxdb

- name: add influxdb repo
  yum_repository:
    name: influxdb
    description: InfluxDB Repository - RHEL \$releasever
    baseurl: https://repos.influxdata.com/rhel/\$releasever/\$basearch/stable
    enabled: yes
    gpgcheck: yes
    gpgkey: https://repos.influxdata.com/influxdb.key

- name: install influxdb
  yum:
    name: influxdb
    state: latest

- name: stop service
  service:
    name: influxd.service
    state: stopped

- name: retrieve types db
  get_url:
    url: https://raw.githubusercontent.com/collectd/collectd/master/src/types.db
    dest: "{{ influxdb_nfs_mount_path }}/types.db"
    mode: 0755
  become: true
  become_user: "{{ service_user }}"

- name: configure influxdb settings
  blockinfile:
    insertafter: "{{ item.after }}"
    dest: /etc/influxdb/influxdb.conf
    marker: "# {mark} {{ item.mark }} ANSIBLE MANAGED BLOCK #"
    block: "{{ item.block }}"
  with_items:
  - after: ^\[http\]$
    mark: http
    block: |
      enabled = true
      bind-address = ":{{ http_port }}"
  - after: '^\[\[collectd\]\]$'
    mark: collectd
    block: |
      enabled = true
      bind-address = ":{{ collectd_port }}"
      database = "{{ collectd_db }}"
      typesdb = "{{ influxdb_nfs_mount_path }}/types.db"

- name: configure influxdb directories
  lineinfile:
    dest: /etc/influxdb/influxdb.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
  - regexp: dir = .*/meta"
    line: dir = "{{ influxdb_nfs_mount_path }}/meta"
  - regexp: dir = .*/data"
    line: dir = "{{ influxdb_nfs_mount_path }}/data"
  - regexp: wal-dir = .*/wal"
    line: wal-dir = "{{ influxdb_nfs_mount_path }}/wal"

- name: run service as different user
  lineinfile:
    dest: /usr/lib/systemd/system/influxdb.service
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
  - { regexp: ^User=, line: "User={{ service_user }}" }
  - { regexp: ^Group=, line: "Group={{ service_group }}" }

- name: change service ownership
  file:
    dest: "{{ item }}"
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
  with_items:
  - /usr/bin/influxd
  - /etc/influxdb/influxdb.conf

- name: systemd reload
  systemd:
    daemon_reload: yes

- name: enable service
  service:
    name: influxd.service
    enabled: yes

- name: start service
  service:
    name: influxd.service
    state: restarted

- name: wait for port
  wait_for:
    port: 8086
    delay: 5

- name: create databases
  influxdb_database:
    hostname: "0.0.0.0"
    database_name: "{{ item }}"  
  with_items:
  - "{{ collectd_db }}"
  - "{{ telegraf_db }}"

- name: create {{ collectd_db }} users
  influxdb_user:
    user_name: "{{ item.user }}"
    user_password: "{{ item.pass }}"
    grants:
    - database: "{{ item.db }}"
      privilege: "{{ item.privilege }}"
  with_items:
  - user: "{{ influxdb_collectd_writer_user }}"
    pass: "{{ influxdb_collectd_writer_pass }}"
    db: "{{ collectd_db }}"
    privilege: "WRITE"
  - user: "{{ influxdb_collectd_reader_user }}"
    pass: "{{ influxdb_collectd_reader_pass }}"
    db: "{{ collectd_db }}"
    privilege: "READ"
  - user: "{{ influxdb_telegraf_writer_user }}"
    pass: "{{ influxdb_telegraf_writer_pass }}"
    db: "{{ telegraf_db }}"
    privilege: "WRITE"
  - user: "{{ influxdb_telegraf_reader_user }}"
    pass: "{{ influxdb_telegraf_reader_pass }}"
    db: "{{ telegraf_db }}"
    privilege: "READ"
