---

- name: centos | disable firewalld
  import_tasks: firewalld.yaml
  when: is_centos

- name: create local mnt dirs
  file:
    path: "{{ item }}"
    state: directory
  with_items: "{{ dirs }}"
  when: create_mnt_dirs

- name: centos | install packages
  become: yes
  dnf:
    name:
    - iscsi-initiator-utils
    - nfs-utils
    state: latest
  vars:
    ansible_python_interpreter: "{{ '/usr/libexec/platform-python' if is_centos else '/usr/bin/python3' }}" # remove when migrated away from centos_7
  when: is_centos

- name: enable service
  service:
    name: iscsid
    enabled: yes
    state: started
