---

- name: centos | disable firewalld
  import_tasks: firewalld.yaml
  when: is_centos

- name: create local mnt dirs
  file:
    path: "{{ item }}"
    state: directory
  with_items: "{{ dirs }}"
  when: create_mnt_dirs

- name: centos | install packages
  become: yes
  dnf:
    name:
    - iscsi-initiator-utils
    - nfs-utils
    state: latest
  when: is_centos

- name: debian | install packages
  become: yes
  apt:
    name: open-iscsi
    state: latest
  when: is_debian

- name: enable service
  service:
    name: iscsid
    enabled: yes
    state: started
