---

- name: install collectd
  apt:
    name: ["collectd", "collectd-utils"]
    state: present

- name: configure collectd settings
  lineinfile:
    dest: /etc/collectd/collectd.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
  - regexp: Hostname\s
    line: Hostname "{{ inventory_hostname }}"
  - regexp: '^#BaseDir "/var/lib/collectd"$'
    line: BaseDir "/var/lib/collectd"
  - regexp: '^#PluginDir "/usr/lib/collectd"$'
    line: PluginDir "/usr/lib/collectd"
  - regexp: TypesDB\s
    line: TypesDB "/usr/share/collectd/types.db"
  - regexp: '^#LoadPlugin network$'
    line: LoadPlugin network

- name: configure influxdb network
  blockinfile:
    dest: /etc/collectd/collectd.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK #"
    block: |
      <Plugin network>
        Server "{{ config_influxdb['host'] }}" "{{ config_influxdb['port'] }}"
      </Plugin>

- name: restart collectd
  service:
    name: collectd
    state: restarted
