---

- name: install collectd
  yum:
    name:
    - collectd
    - collectd-rrdtool
    state: present

- name: configure settings
  lineinfile:
    dest: /etc/collectd.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
  - regexp: Hostname\s
    line: Hostname "{{ inventory_hostname }}"
  - regexp: TypesDB\s
    line: TypesDB "/usr/share/collectd/types.db"
  - regexp: ^[#]?BaseDir\s
    line: BaseDir "/var/lib/collectd"
  - regexp: ^[#]?PluginDir\s
    line: PluginDir "/usr/lib64/collectd"
  - regexp: ^[#]?Interval\s
    line: Interval 60

- name: load plugins
  lineinfile:
    dest: /etc/collectd.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertafter: ^TypesDB\s
    state: present
  with_items:
  - regexp: '^LoadPlugin network$'
    line: LoadPlugin network

- name: configure influxdb network
  blockinfile:
    dest: /etc/collectd.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK #"
    block: |
      <Plugin network>
        Server "{{ influxdb_host }}" "{{ influxdb_port }}"
      </Plugin>

- name: restart collectd
  service:
    name: collectd
    state: restarted
