---


- name: centos | open postgresql services
  include_role:
    name: services/firewalld/tasks
  vars:
    name: postgresql
    services:
    - name: postgresql
      service: postgresql
    ports:
    - name: postgresql monitoring
      port: 9187/tcp
