- name: create network
  docker_network:
    name: postgres

- name: create service dirs
  file:
    group: nobody
    mode: "0777"
    owner: nobody
    path: "{{ item.path }}"
    state: directory
  with_items:
    - path: /opt/postgres

- name: start container
  become: true
  docker_container:
    env:
      POSTGRES_USER: "{{ global.postgresql.username }}"
      POSTGRES_PASSWORD: "{{ global.postgresql.password }}"
      PGDATA: /var/lib/postgresql/data/data
      PGUSER: postgres
    image: bitnami/postgresql:15.8.0
    name: postgres
    networks:
      - name: postgres
    ports:
      - 5432:5432
    restart_policy: always
    volumes:
      - /opt/postgres:/var/lib/postgresql/data

- name: start exporter container
  become: true
  docker_container:
    env:
      DATA_SOURCE_URI: "postgres:5432/?sslmode=disable"
      DATA_SOURCE_USER: "{{ global.postgresql.username }}"
      DATA_SOURCE_PASS: "{{ global.postgresql.password }}"
    image: quay.io/prometheuscommunity/postgres-exporter:v0.15.0
    name: postgresql-metrics
    networks:
      - name: postgres
    ports:
      - 9187:9187
    restart_policy: unless-stopped

- name: centos | open firewalld ports
  import_tasks: firewalld.yaml
  when: is_centos
