---

- name: Set the hostname
  become: yes
  command: hostnamectl set-hostname "{{ inventory_hostname }}"

- name: Update /etc/hosts with new hostname (pi)
  become: yes
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.1.1\t"
    line: "127.0.1.1\t{{ inventory_hostname}}"
    state: present
  when: "'rpi' in group_names"

- name: Update /etc/hosts with new hostname
  become: yes
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost.localdomain\tlocalhost$'
    line: "127.0.0.1\tlocalhost.localdomain\tlocalhost\t{{ inventory_hostname }}"
    state: present
  when: "'rpi' not in group_names"

- name: Update cloud.cfg to preserve hostname
  become: yes
  lineinfile:
    dest: /etc/cloud/cloud.cfg
    regexp: '^preserve_hostname: false$'
    line: "preserve_hostname: true"
    state: present
  when: "'rpi' not in group_names"
