- name: postgresql | create guacamole database
  include_role:
    name: docker/postgresql/initdb
  vars:
    postgresql_host: "{{ global.postgresql.host }}"
    postgresql_port: "{{ global.postgresql.port }}"
    postgresql_user: "{{ global.postgresql.user }}"
    postgresql_pass: "{{ global.postgresql.pass }}"
    database_name: "{{ global.guacamole.db.name }}"
    database_user: "{{ global.guacamole.db.user }}"
    database_pass: "{{ global.guacamole.db.pass }}"

- name: check if guacamole initdb script exists
  stat:
    path: /tmp/initdb.sh
  register: initdb

- name: initialize guacamole database
  block:
    - name: get guacamole initdb script
      become: true
      docker_container:
        name: guacamole-tmp
        image: guacamole/guacamole
        command: /opt/guacamole/bin/initdb.sh --postgres
        detach: no
        cleanup: yes
        state: started
      register: guacamole

    - name: write guacamole initdb to file
      copy:
        content: "{{ global.guacamole.ansible_facts.docker_container.Output }}"
        dest: /tmp/initdb.sh

    - name: run guacamole initdb script
      postgresql_query:
        login_host: "{{ global.postgresql.host }}"
        login_user: "{{ global.postgresql.user }}"
        login_password: "{{ global.postgresql.pass }}"
        db: "{{ global.guacamole.db.name }}"
        path_to_script: /tmp/initdb.sh
  when: initdb.stat.exists == false
