---

- name: initialize guacamole db
  import_tasks: initialize.yaml
  when: initialize

- name: launch guacd container
  docker_container:
    name: guacd
    image: guacamole/guacd
    restart_policy: unless-stopped

- name: launch guacamole container
  docker_container:
    name: guacamole
    image: "guacamole/guacamole:{{ global.guacamole.tag }}"
    restart_policy: unless-stopped
    links:
    - guacd:guacd
    env:
      POSTGRES_HOSTNAME: "{{ global.postgresql.host }}"
      POSTGRES_DATABASE: "{{ global.guacamole.db.name }}"
      POSTGRES_USER: "{{ global.guacamole.db.user }}"
      POSTGRES_PASSWORD: "{{ global.guacamole.db.pass }}"
      OPENID_ISSUER: "{{ global.guacamole.openid.issuer }}"
      OPENID_JWKS_ENDPOINT: "{{ global.guacamole.openid.jwks_endpoint }}"
      OPENID_AUTHORIZATION_ENDPOINT: "{{ global.guacamole.openid.auth_endpoint }}"
      OPENID_CLIENT_ID: "{{ global.guacamole.openid.client_id }}"
      OPENID_SCOPE: "{{ global.guacamole.openid.scope }}"
      OPENID_REDIRECT_URI: "{{ global.guacamole.openid.redirect_uri }}"
      OPENID_USERNAME_CLAIM_TYPE: "{{ global.guacamole.openid.username_claim }}"
    ports:
    - 80:8080

- name: add guacamole openid extension
  shell: |
    docker exec guacamole sh \
      -l \
      -c "wget http://archive.apache.org/dist/guacamole/1.2.0/binary/guacamole-auth-openid-1.2.0.tar.gz -O \$HOME/.guacamole/extensions/guacamole-auth-openid-1.2.0.tar.gz"

- name: restart guacamole container
  docker_container:
    name: guacamole
    restart: yes

- name: create guacamole network
  docker_network:
    name: guacamole
    connected:
    - guacd
    - guacamole

- name: centos | open firewalld ports
  import_tasks: firewalld.yaml
  when: is_centos
