---

- name: install duo packages
  dnf:
    name:
    - duo_unix
    state: present
  vars:
    ansible_python_interpreter: /usr/libexec/platform-python # required for centos7, python3.8 unable to import dnf

- name: configure duo settings
  lineinfile:
    dest: /etc/duo/login_duo.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
  - { regexp: ^ikey =, line: "ikey = {{ global.bastion.duo.ikey }}" }
  - { regexp: ^skey =, line: "skey = {{ global.bastion.duo.skey }}" }
  - { regexp: ^host =, line: "host = {{ global.bastion.duo.host }}" }
