---

- name: install duo packages
  yum:
    name:
    - duo_unix
    state: present

- name: configure duo settings
  lineinfile:
    dest: /etc/duo/login_duo.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
  - { regexp: ^ikey =, line: "ikey = {{ bastion.duo.ikey }}" }
  - { regexp: ^skey =, line: "skey = {{ bastion.duo.skey }}" }
  - { regexp: ^host =, line: "host = {{ bastion.duo.host }}" }
