---

- name: create env
  copy:
    src: .env
    dest: /etc/grafana.env
    force: no
    group: root
    owner: root
    mode: 0755

- name: create volumes
  docker_volume:
    name: "{{ item.name }}"
    driver_options:
      type: nfs
      device: ":/{{ item.mount }}"
      o: "addr={{ nfs_host }},vers=4,tcp,rw,port=2049"
  with_items:
  - name: conf
    mount: "{{ conf_mount }}"

- name: start container
  docker_container:
    name: grafana
    image: grafana/grafana:latest
    restart_policy: unless-stopped
    env_file: /etc/grafana.env
    user: "{{ grafana_docker_user_id }}:0"
    ports:
    - 80:3000
    volumes:
    - conf:/var/lib/grafana
