---

- name: centos | install fail2ban packages
  dnf:
    name:
    - fail2ban
    - fail2ban-systemd
    state: latest
  vars:
    ansible_python_interpreter: "{{ '/usr/libexec/platform-python' if is_centos else '/usr/bin/python3' }}" # remove when migrated away from centos_7
  notify: enable fail2ban
