- name: disable root login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: "^PermitRootLogin", line: "PermitRootLogin no" }
  notify: restart ssh

- name: disable password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: "^PasswordAuthentication", line: "PasswordAuthentication no" }
  when: is_freeipa
  notify: restart ssh

- name: disable challenge response authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - {
        regexp: "^ChallengeResponseAuthentication yes",
        line: "ChallengeResponseAuthentication no",
      }
  when: is_freeipa and not is_bastion
  notify: restart ssh

- name: configure bastion host access
  block:
    - name: block access to non bastion user from bastion host
      blockinfile:
        dest: /etc/ssh/sshd_config
        marker: "# {mark}-block-bastion"
        block: |
          Match User *,!{{ global.bastion.user }} Address {{ global.bastion.host }}
            ForceCommand /bin/false
      when: is_freeipa and (global.bastion.user and global.bastion.host)
      notify: restart ssh

    - name: block access from bastion host if not registered on freeipa
      blockinfile:
        dest: /etc/ssh/sshd_config
        marker: "# {mark}-block-bastion"
        block: |
          Match Address {{ global.bastion.host }}
            ForceCommand /bin/false
      when: not is_freeipa and global.bastion.host
      notify: restart ssh
  when: (global.bastion is defined) and not is_bastion

- name: centos | install fail2ban
  import_tasks: centos.yaml
  when: is_centos

- name: debian | install fail2ban
  import_tasks: debian.yaml
  when: is_debian

- name: configure fail2ban jail
  blockinfile:
    dest: /etc/fail2ban/jail.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK #"
    block: |
      [sshban]
      enabled   = true
      port      = ssh
      logpath   = %(sshd_log)s
      banaction = iptables-allports
      maxretry  = 10
      bantime   = 86400
      filter    = sshd
  notify: restart fail2ban
