---

- name: create volumes
  docker_volume:
    name: "{{ item.name }}"
    driver_options:
      type: nfs
      device: ":/{{ item.mount }}"
      o: "addr={{ nfs_host }},vers=4,tcp,rw,port=2049"
  with_items:
  - name: data
    mount: "{{ data_mount }}"

- name: start container
  docker_container:
    name: es
    image: elasticsearch:6.8.5
    restart_policy: unless-stopped
    user: "{{ es_docker_user_id }}:0"
    env:
      "node.name": es00
      "cluster.name": es-docker-cluster
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms1024m -Xmx1024m
    ports:
    - 9200:9200
    - 9300:9300
    volumes:
    - data:/usr/share/elasticsearch/data
