- name: centos | add docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: centos | install docker dependencies
  dnf:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: latest

- name: centos | install docker packages
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
