---
- name: centos | Install packages
  ansible.builtin.import_tasks: centos.yaml
  when: is_centos

- name: debian | Install packages
  ansible.builtin.import_tasks: debian.yaml
  when: is_debian

- name: Enable service
  ansible.builtin.service:
    name: docker
    enabled: true

- name: Start service
  ansible.builtin.service:
    name: docker
    state: started

- name: Install docker pip using python3
  become: false
  ansible.builtin.pip:
    name:
      - docker

- name: Log into docker
  become: true
  community.docker.docker_login:
    username: "{{ homelab.docker.username }}"
    password: "{{ homelab.docker.password }}"
