---

- name: centos | install packages
  import_tasks: centos.yaml
  when: is_centos

- name: debian | install packages
  import_tasks: debian.yaml
  when: is_debian

- name: enable service
  service:
    name: docker
    enabled: yes

- name: start service
  service:
    name: docker
    state: started

- name: install docker pip using python3
  become: no
  pip:
    name:
    - docker
    extra_args: --user

- name: log into docker
  docker_login:
    username: "{{ global.docker.username }}"
    password: "{{ global.docker.password }}"
    email: "{{ global.docker.email }}"
