- name: centos | install packages
  import_tasks: centos.yaml
  when: is_centos

- name: debian | install packages
  import_tasks: debian.yaml
  when: is_debian

- name: enable service
  service:
    name: docker
    enabled: yes

- name: start service
  service:
    name: docker
    state: started

- name: install docker pip using python3
  become: false
  pip:
    name:
      - docker

- name: log into docker
  become: true
  docker_login:
    username: "{{ global.docker.username }}"
    password: "{{ global.docker.password }}"
