---

- name: jetbrains | set facts
  set_fact:
    install_path: "/opt/jetbrains-toolbox-{{ global.version.jetbrains }}"

- name: jetbrains | create install dir
  become: true
  file:
    path: "{{ install_path }}"
    state: directory

- name: jetbrains | download and untar
  become: true
  unarchive:
    remote_src: yes
    src: "https://download.jetbrains.com/toolbox/jetbrains-toolbox-{{ global.version.jetbrains }}.tar.gz"
    dest: "{{ install_path }}"
    extra_opts:
    - --strip-components=1

- name: jetbrains | remove toolbox from autostart
  become: false
  file:
    path: "{{ ansible_env['HOME'] }}/.config/autostart/jetbrains-toolbox.desktop"
    state: absent
