---

- name: centos | open spacewalk client services
  include_role:
    name: services/firewalld/tasks
  vars:
    name: spacewalk client
    services:
    - name: spacewalk client
      service: ssh
    ports:
    - name: spacewalk client
      port: 5222/tcp
