---

- name: centos | install spacewalk
  block:
  - name: centos | install spacewalk server ca
    yum:
      name: "http://{{ spacewalk.host }}/pub/rhn-org-trusted-ssl-cert-1.0-5.noarch.rpm"
      state: present
      disable_gpg_check: yes
      validate_certs: no

  - name: centos8 | install spacewalk
    block:
    - name: centos8 | add spacewalk repo
      yum_repository:
        name: spacewalk-client
        description: Spacewalk Client EPEL
        baseurl: http://mirrors.maine.edu/spacewalk/nightly-client/RHEL/8/x86_64/
        gpgcheck: no

    - name: centos8 | install spacewalk packages
      dnf:
        name:
        - rhn-client-tools
        - rhn-check
        - rhn-setup
        - rhnsd
        - yum-rhn-plugin
        - osad
        state: latest

    - name: centos8 | register to centos channel
      rhn_register:
        state: present
        activationkey: 1-centos8-base
        server_url: https://{{ spacewalk.host }}/XMLRPC
      when: not is_docker and not is_kubernetes
      ignore_errors: yes

    - name: centos8 | configure spacewalk repo plugin
      lineinfile:
        dest: /etc/yum/pluginconf.d/spacewalk.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
      - regexp: ^gpgcheck
        line: gpgcheck = 0
      - regexp: ^enabled
        line: enabled = 1

    - name: centos8 | enable rhnsd
      service:
        name: rhnsd
        state: started
        enabled: yes
    when: is_centos_8

  - name: centos7 | install spacewalk
    block:
    - name: centos7 | install repo dependencies
      yum:
        name:
        - epel-release
        state: present

    - name: centos7 | add spacewalk repo
      yum_repository:
        name: spacewalk-client
        description: Spacewalk Client EPEL
        baseurl: http://mirrors.maine.edu/spacewalk/2.10-client/RHEL/7/x86_64/
        gpgcheck: no

    - name: centos7 | install spacewalk packages
      yum:
        name:
        - rhn-client-tools
        - rhn-check
        - rhn-setup
        - rhnsd
        - yum-rhn-plugin
        - m2crypto
        - osad
        state: present

    - name: centos7 | register to centos channel
      rhn_register:
        state: present
        activationkey: 1-centos7-base
        server_url: https://{{ spacewalk.host }}/XMLRPC
      when: not is_docker and not is_kubernetes
      ignore_errors: yes

    - name: centos7 | register to docker channel
      rhn_register:
        state: present
        activationkey: 1-centos7-docker
        server_url: https://{{ spacewalk.host }}/XMLRPC
      when: is_docker
      ignore_errors: yes

    - name: centos7 | register to kubernetes channel
      rhn_register:
        state: present
        activationkey: 1-centos7-kubernetes
        server_url: https://{{ spacewalk.host }}/XMLRPC
      when: is_kubernetes
      ignore_errors: yes

    - name: centos7 | register to duo channel
      rhn_register:
        state: present
        activationkey: 1-centos7-duo
        server_url: https://{{ spacewalk.host }}/XMLRPC
      when: run_bastion_setup
      ignore_errors: yes

    - name: centos7 | configure spacewalk repo plugin
      lineinfile:
        dest: /etc/yum/pluginconf.d/rhnplugin.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
      - regexp: ^gpgcheck
        line: gpgcheck = 0
      - regexp: ^enabled
        line: enabled = 1

    - name: centos7 | enable rhnsd timer
      service:
        name: rhnsd.timer
        state: started
        enabled: yes
    when: is_centos_7

  - name: centos | remove spacewalk client repo
    yum_repository:
      name: spacewalk-client
      state: absent

  - name: centos | enable osad
    service:
      name: osad
      state: started
      enabled: yes

  - name: centos | open firewalld ports
    import_tasks: firewalld.yaml
    when: not is_kubernetes # kubernetes clients disable firewall
  when: is_centos
