global:
  reboot:
    min_wait_time: 15
    max_wait_time: 30
  ipa:
    user: hugo

  version:
    # auth
    keycloak: "26.5.0"
    pomerium: "v0.32.0"

    # media
    calibre_web: "0.6.26"
    ghost: "6.21.0"
    gramps: "26.2.0"
    miniflux: "2.2.17"
    ombi: "4.55.7-development"
    tautulli: "v2.16.1"

    # pirate
    calibre: "8.0.0"
    flaresolverr: "v3.4.6"
    jackett: "0.24.1287"
    radarr: "6.0.4"
    readarr: "0.4.18-develop"
    sabnzbd: "4.5.5"
    sonarr: "4.0.16"
    transmission: "4.1.1"

  bastion:
    user: ""
    host: ""
    duo:
      ikey: "{{ vault_bastion_duo_ikey }}"
      skey: "{{ vault_bastion_duo_skey }}"
      host: ""

  collectd:
    # host: asgard.udp.internal.cluster.homelabops.dev
    host: ops.internal.corteshq.net
    port: "25826"

  docker:
    username: ""
    password: "{{ vault_docker_password }}"
    email: ""

  grafana:
    oidc_client_secret: "{{ vault_grafana_oidc_client_secret }}"
    smtp_password: "{{ vault_grafana_smtp_password }}"

  gramps:
    oidc_client_secret: "{{ vault_gramps_oidc_client_secret }}"
    smtp_password: "{{ vault_gramps_smtp_password }}"

  influxdb:
    password: "{{ vault_influxdb_password }}"
    username: root

  media:
    nfs:
      plex: ""
      plexlogs: /volume1/services/plex/logs
      movies: /volume1/media/movies
      tvshows: /volume1/media/tv-shows
      xxx: /volume1/media/x

  miniflux:
    admin_password: "{{ vault_miniflux_admin_password }}"
    oidc_client_secret: "{{ vault_miniflux_oidc_client_secret }}"

  mysql:
    password: "{{ vault_mysql_password }}"
    ombi:
      database: ombi
      password: "{{ vault_mysql_ombi_password }}"
      username: ombi

  nfs:
    host: nas.internal.corteshq.net

  pirate:
    nfs:
      downloads: /volume1/media/downloads
      ebooks: /volume1/media/ebooks
      movies: /volume1/media/movies
      tv: /volume1/media/tv-shows

  plex:
    claim: "{{ vault_plex_claim }}"

  postgresql:
    username: postgres
    password: "{{ vault_postgresql_password }}"
    gramps:
      database:
        search: gramps_cortes
        user: gramps_user
      password: "{{ vault_postgresql_gramps_password }}"
      username: gramps
    miniflux:
      database: miniflux
      password: "{{ vault_postgresql_miniflux_password }}"
      username: miniflux
    keycloak:
      database: keycloak
      password: "{{ vault_postgresql_keycloak_password }}"
      username: keycloak

  server:
    nfs:
      grafana: /volume1/services/docker/grafana
      influxdb: /volume1/services/docker/influxdb
      influxdb_config: /volume1/services/docker/influxdb-config
      influxdb_startup: /volume1/services/docker/influxdb-startup
      loki: /volume1/services/docker/loki
      prometheus: /volume1/services/docker/prometheus
      prometheus_config: /volume1/services/docker/prometheus-config

  sish:
    tag: ""
    sshPort: "8022"
    forwardingPorts:
      http: "80"
      https: "443"
      tcp: []
    domain: ""
    privateKeyPassphrase: "{{ vault_sish_private_key_passphrase }}"

  spin_cli:
    gate:
      endpoint: https://spinnaker-api.domain
    auth:
      enabled: true
      oauth2:
        tokenUrl: https://auth.domain/auth
        authUrl: https://auth.domain/token
        clientId: ""
        clientSecret: "{{ vault_spin_cli_oauth2_client_secret }}"
        scopes:
          - openid
          - email
          - profile
