---
- name: centos | Open calibre services
  ansible.builtin.include_role:
    name: services/firewalld
  vars:
    firewalld_rule_name: calibre
    firewalld_ports:
      - name: calibre
        port: 8083/tcp

- name: centos | Open gramps services
  ansible.builtin.include_role:
    name: services/firewalld
  vars:
    firewalld_rule_name: gramps
    firewalld_ports:
      - name: gramps
        port: 5000/tcp

- name: centos | Open miniflux services
  ansible.builtin.include_role:
    name: services/firewalld
  vars:
    firewalld_rule_name: miniflux
    firewalld_ports:
      - name: miniflux
        port: 8080/tcp

- name: centos | Open ombi services
  ansible.builtin.include_role:
    name: services/firewalld
  vars:
    firewalld_rule_name: ombi
    firewalld_ports:
      - name: ombi
        port: 3579/tcp

- name: centos | Open plex services
  ansible.builtin.include_role:
    name: services/firewalld
  vars:
    firewalld_rule_name: plex
    firewalld_ports:
      - name: plex
        port: 32400/tcp

- name: centos | Open tautulli services
  ansible.builtin.include_role:
    name: services/firewalld
  vars:
    firewalld_rule_name: tautulli
    firewalld_ports:
      - name: tautulli
        port: 8181/tcp
