- name: centos | open calibre services
  include_role:
    name: services/firewalld
  vars:
    firewalld_rule_name: calibre
    firewalld_ports:
      - name: calibre
        port: 8083/tcp

- name: centos | open gramps services
  include_role:
    name: services/firewalld
  vars:
    firewalld_rule_name: gramps
    firewalld_ports:
      - name: gramps
        port: 5000/tcp

- name: centos | open miniflux services
  include_role:
    name: services/firewalld
  vars:
    firewalld_rule_name: miniflux
    firewalld_ports:
      - name: miniflux
        port: 8080/tcp

- name: centos | open ombi services
  include_role:
    name: services/firewalld
  vars:
    firewalld_rule_name: ombi
    firewalld_ports:
      - name: ombi
        port: 3579/tcp

- name: centos | open plex services
  include_role:
    name: services/firewalld
  vars:
    firewalld_rule_name: plex
    firewalld_ports:
      - name: plex
        port: 32400/tcp

- name: centos | open tautulli services
  include_role:
    name: services/firewalld
  vars:
    firewalld_rule_name: tautulli
    firewalld_ports:
      - name: tautulli
        port: 8181/tcp
