- name: create transcode dir
  file:
    path: /dev/shm/plex
    owner: nobody
    group: nobody
    state: directory
    mode: "0777"

- name: create service dirs
  file:
    group: nobody
    mode: "0777"
    owner: nobody
    path: "{{ item.path }}"
    state: directory
  with_items:
    - path: /opt/calibre
    - path: /opt/gramps
    - path: /opt/gramps/cache
    - path: /opt/gramps/db
    - path: /opt/gramps/index
    - path: /opt/gramps/media
    - path: /opt/gramps/secret
    - path: /opt/gramps/thumbnail
    - path: /opt/gramps/tmp
    - path: /opt/gramps/users
    - path: /opt/ombi
    - path: /opt/plex
    - path: /opt/tautulli

- name: create plex nfs volumes
  become: true
  docker_volume:
    name: "{{ item.name }}"
    driver_options:
      type: nfs
      device: ":/{{ item.mount }}"
      o: "addr={{ global.nfs.host }},nfsvers=4,vers=4,tcp,rw,port=2049"
  with_items:
    - name: plexlogs
      mount: "{{ global.media.nfs.plexlogs }}"
    - name: ebooks
      mount: "{{ global.pirate.nfs.ebooks }}"
    - name: movies
      mount: "{{ global.media.nfs.movies }}"
    - name: tvshows
      mount: "{{ global.media.nfs.tvshows }}"

- name: allow plex ssl cert to be readable
  file:
    dest: "/etc/ssl/{{ ansible_host }}/{{ ansible_host }}.pk12"
    owner: root
    group: root
    mode: "0644"

- name: start calibre container
  become: true
  docker_container:
    env:
      TZ: America/Los_Angeles
    image: linuxserver/calibre-web:{{ global.version.calibre_web }}
    name: calibre
    ports:
      - 8083:8083
    restart_policy: always
    volumes:
      - /opt/calibre:/config
      - ebooks:/books

- name: start gramps container
  become: true
  docker_container:
    env:
      GRAMPSWEB_BASE_URL: https://tree.corteshq.net/

      GRAMPSWEB_EMAIL_HOST: smtp.zoho.com
      GRAMPSWEB_EMAIL_PORT: "465"
      GRAMPSWEB_EMAIL_HOST_USER: no-reply@homelabops.dev
      GRAMPSWEB_EMAIL_HOST_PASSWORD: "{{ global.gramps.smtp_password }}"
      GRAMPSWEB_EMAIL_USE_SSL: "False"
      GRAMPSWEB_EMAIL_USE_STARTTLS: "False"
      GRAMPSWEB_DEFAULT_FROM_EMAIL: no-reply@corteshq.net

      GRAMPSWEB_OIDC_AUTO_REDIRECT: "True"
      GRAMPSWEB_OIDC_CLIENT_ID: tree
      GRAMPSWEB_OIDC_CLIENT_SECRET: "{{ global.gramps.oidc_client_secret }}"
      GRAMPSWEB_OIDC_DISABLE_LOCAL_AUTH: "True"
      GRAMPSWEB_OIDC_ENABLED: "True"
      GRAMPSWEB_OIDC_GROUP_ADMIN: admin
      GRAMPSWEB_OIDC_GROUP_CONTRIBUTOR: contributor
      GRAMPSWEB_OIDC_GROUP_EDITOR: editor
      GRAMPSWEB_OIDC_GROUP_MEMBER: member
      GRAMPSWEB_OIDC_ISSUER: https://auth.corteshq.net/realms/apps
      GRAMPSWEB_OIDC_NAME: CortesHQ
      GRAMPSWEB_OIDC_SCOPES: openid email profile
      GRAMPSWEB_OIDC_ROLE_CLAIM: roles

      GRAMPSWEB_REGISTRATION_DISABLED: "True"

      GRAMPSWEB_TREE: gramps
      # doesn't work :(
      # GRAMPSWEB_POSTGRES_HOST: postgres
      # GRAMPSWEB_POSTGRES_PASSWORD: "{{ global.postgresql.gramps.password }}"
      # GRAMPSWEB_POSTGRES_USER: "{{ global.postgresql.gramps.username }}"
      # GRAMPSWEB_DB_URI: postgresql://{{ global.postgresql.gramps.username }}:{{ global.postgresql.gramps.password }}@postgres:5432/{{ global.postgresql.gramps.database.search }}

      GRAMPSWEB_SEARCH_INDEX_DB_URI: "postgresql://{{ global.postgresql.gramps.username }}:{{ global.postgresql.gramps.password }}@postgres:5432/{{ global.postgresql.gramps.database.search }}"
      GRAMPSWEB_USER_DB_URI: "postgresql://{{ global.postgresql.gramps.username }}:{{ global.postgresql.gramps.password }}@postgres:5432/{{ global.postgresql.gramps.database.user }}"
    image: ghcr.io/gramps-project/grampsweb:{{ global.version.gramps }}
    name: gramps
    networks:
      - name: postgres
    ports:
      - 5000:5000
    restart_policy: always
    volumes:
      - /opt/gramps/thumbnail:/app/thumbnail_cache
      - /opt/gramps/cache:/app/cache
      - /opt/gramps/secret:/app/secret
      - /opt/gramps/db:/root/.gramps
      - /opt/gramps/media:/app/media
      - /opt/gramps/tmp:/tmp
      - /opt/gramps/users:/app/users
      - /opt/gramps/index:/app/indexdir

- name: start miniflux container
  become: true
  docker_container:
    env:
      RUN_MIGRATIONS: "1"
      CREATE_ADMIN: "0"
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: "{{ global.miniflux.admin_password }}"
      DATABASE_URL: "postgres://{{ global.postgresql.miniflux.username }}:{{ global.postgresql.miniflux.password }}@postgres:5432/{{ global.postgresql.miniflux.database }}?sslmode=disable"
      OAUTH2_PROVIDER: oidc
      OAUTH2_CLIENT_ID: miniflux
      OAUTH2_CLIENT_SECRET: "{{ global.miniflux.oidc_client_secret }}"
      OAUTH2_REDIRECT_URL: https://miniflux.corteshq.net/oauth2/oidc/callback
      OAUTH2_OIDC_DISCOVERY_ENDPOINT: https://auth.corteshq.net/realms/master
      OAUTH2_USER_CREATION: "1"
    image: miniflux/miniflux:{{ global.version.miniflux }}
    name: miniflux
    networks:
      - name: postgres
    ports:
      - 8080:8080
    restart_policy: always

- name: start ombi container
  become: true
  docker_container:
    env:
      MYSQL_DATABASE: "{{ global.mysql.ombi.database }}"
      MYSQL_PASSWORD: "{{ global.mysql.ombi.password }}"
      MYSQL_USER: "{{ global.mysql.ombi.username }}"
      TZ: America/Los_Angeles
    image: linuxserver/ombi:{{ global.version.ombi }}
    name: ombi
    networks:
      - name: mysql
    ports:
      - 3579:3579
    restart_policy: always
    volumes:
      - /opt/ombi:/config

- name: start plex container
  become: true
  docker_container:
    name: plex
    image: plexinc/pms-docker:plexpass
    network_mode: host
    restart_policy: always
    env:
      ADVERTISE_IP: "http://{{ ansible_host }}:32400"
      CHANGE_CONFIG_DIR_OWNERSHIP: "false"
      PLEX_CLAIM: "{{ global.plex.claim }}"
      TV: America/Los_Angeles
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    devices:
      # tv tuner
      # need to look into how to fix this
      # - /dev/dvb:/dev/dvb
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /etc/ssl/{{ ansible_host }}/{{ ansible_host }}.pk12:/etc/ssl/cert.pk12
      - /dev/shm/plex:/transcode
      - /opt/plex:/config
      - movies:/data/movies
      - plexlogs:/config/Library/Application Support/Plex Media Server/Logs
      - tvshows:/data/tv-shows

- name: start tautulli container
  become: true
  docker_container:
    env:
      TZ: America/Los_Angeles
    image: tautulli/tautulli:{{ global.version.tautulli }}
    name: tautulli
    ports:
      - 8181:8181
    restart_policy: always
    volumes:
      - /opt/tautulli:/config
      - plexlogs:/tautulli_logs:ro

- name: centos | open firewalld ports
  import_tasks: firewalld.yaml
  when: is_centos

- name: check for private tasks
  stat:
    path: "{{ role_path }}/tasks/private.yaml"
  register: _private_tasks

- name: include private tasks
  include_tasks: private.yaml
  when: _private_tasks.stat.exists
