---

- name: create transcode dir
  file:
    # path: /dev/shm/plex
    path: /tmp/plex
    owner: nobody
    group: nobody
    state: directory
    mode: "0777"

- name: check /mnt/plex exists
  stat:
    path: /mnt/plex
  register: config_mnt

- name: create /mnt/plex dir
  file:
    path: /mnt/plex
    owner: nobody
    group: nobody
    state: directory
    mode: "0777"
  when: config_mnt.stat.exists == false

- name: mount plex dir
  mount:
    path: /mnt/plex
    src: "{{ global.nfs.host }}:{{ global.media.nfs.plex }}"
    fstype: nfs4
    opts: defaults,proto=tcp,port=2049,rw
    state: mounted

# TODO switch to iscsi instead of nfs
# sqlite sucks if being used over nfs...
- name: check /opt/plex exists
  stat:
    path: /opt/plex
  register: config

- name: seed /opt/plex directory
  block:
  - name: create /opt/plex dir
    file:
      path: /opt/plex
      owner: nobody
      group: nobody
      state: directory
      mode: "0777"

  - name: ensure plex container is stopped
    docker_container:
      name: plex
      state: stopped
    ignore_errors: yes

  - name: dump nfs to /opt/plex
    shell: cp -fvpr /mnt/plex/* /opt/plex/

  - name: chmod to 777
    file:
      path: /opt/plex
      mode: "0777"
      state: directory
      recurse: yes
  when: config.stat.exists == false

- name: create plex nfs volumes
  docker_volume:
    name: "{{ item.name }}"
    driver_options:
      type: nfs
      device: ":/{{ item.mount }}"
      o: "addr={{ global.nfs.host }},nfsvers=4,vers=4,tcp,rw,port=2049"
  with_items:
  # - name: plex
  #   mount: "{{ global.media.nfs.plex }}"
  - name: movies
    mount: "{{ global.media.nfs.movies }}"
  - name: tvshows
    mount: "{{ global.media.nfs.tvshows }}"

- name: allow plex ssl cert to be readable
  file:
    dest: "/etc/ssl/{{ ansible_host }}/{{ ansible_host }}.pk12"
    owner: root
    group: root
    mode: "0644"

- name: start plex container
  docker_container:
    name: plex
    image: plexinc/pms-docker:plexpass
    network_mode: host
    restart_policy: unless-stopped
    env:
      ADVERTISE_IP: "https://{{ ansible_host }}:32400"
      CHANGE_CONFIG_DIR_OWNERSHIP: "false"
      PLEX_CLAIM: "{{ global.plex.claim }}"
      TV: America/Los_Angeles
    # devices:
    # - /dev/dri:/dev/dri
    volumes:
    - /etc/ssl/{{ ansible_host }}/{{ ansible_host }}.pk12:/etc/ssl/cert.pk12
    - /tmp/plex:/transcode
    - /opt/plex:/config
    - movies:/data/movies
    - tvshows:/data/tv-shows

- name: centos | open firewalld ports
  import_tasks: firewalld.yaml
  when: is_centos
