---
- name: centos | Open flaresolverr services
  ansible.builtin.include_role:
    name: firewalld
  vars:
    firewalld_rule_name: flaresolverr
    firewalld_ports:
      - name: flaresolverr
        port: 8191/tcp

- name: centos | Open jackett services
  ansible.builtin.include_role:
    name: firewalld
  vars:
    firewalld_rule_name: jackett
    firewalld_ports:
      - name: jackett
        port: 9117/tcp

- name: centos | Open transmission services
  ansible.builtin.include_role:
    name: firewalld
  vars:
    firewalld_rule_name: transmission
    firewalld_ports:
      - name: transmission
        port: 9091/tcp
      - name: transmission-vpn
        port: 54949/tcp
      - name: transmission-vpn-udp
        port: 54949/tcp

- name: centos | Open sabnzbd services
  ansible.builtin.include_role:
    name: firewalld
  vars:
    firewalld_rule_name: sabnzbd
    firewalld_ports:
      - name: sabnzbd
        port: 8080/tcp

- name: centos | Open radarr services
  ansible.builtin.include_role:
    name: firewalld
  vars:
    firewalld_rule_name: radarr
    firewalld_ports:
      - name: radarr
        port: 7878/tcp

- name: centos | Open sonarr services
  ansible.builtin.include_role:
    name: firewalld
  vars:
    firewalld_rule_name: sonarr
    firewalld_ports:
      - name: sonarr
        port: 8989/tcp

- name: centos | Open readarr services
  ansible.builtin.include_role:
    name: firewalld
  vars:
    firewalld_rule_name: readarr
    firewalld_ports:
      - name: readarr
        port: 8787/tcp

- name: centos | Open calibre-server services
  ansible.builtin.include_role:
    name: firewalld
  vars:
    firewalld_rule_name: calibre-server
    firewalld_ports:
      - name: calibre-server
        port: 7070/tcp
      - name: calibre-server
        port: 8081/tcp
