---

- name: istioctl | download
  become: yes
  unarchive:
    remote_src: yes
    src: "https://github.com/istio/istio/releases/download/{{ global.version.istioctl }}/istio-{{ global.version.istioctl }}-linux-amd64.tar.gz"
    dest: /opt/
    owner: "{{ ansible_user }}"

- name: istioctl | create symlink
  become: yes
  file:
    src: "/opt/istio-{{ global.version.istioctl }}/bin/istioctl"
    dest: /usr/local/bin/istioctl
    state: link
    force: yes
