- name: debian | update debian packages
  import_tasks: debian.yaml
  when: is_debian

- name: centos | update centos packages
  import_tasks: centos.yaml
  when: is_centos

- name: update packages for multiple users
  include_tasks: multiple_users.yaml
  with_items: "{{ ansible_users }}"
