---

- name: debian | update apt packages
  import_tasks: apt.yaml
  when: is_debian

- name: centos | update yum packages
  import_tasks: yum.yaml
  when: is_centos

- name: update packages for multiple users
  include_tasks: multiple_users.yaml
  with_items: "{{ ansible_users }}"
