---

- name: debian system update
  block:
  - name: debian - update
    apt:
      name: "*"
      state: latest
  - name: debian - upgrade
    apt:
      upgrade: yes
      update_cache: yes
  when: is_debian

- name: centos system update
  block:
  - name: centos - update
    yum:
      name: "*"
      state: latest
    ignore_errors: yes
  when: is_centos
