---

- name: debian | update apt packages
  import_tasks: apt.yaml
  when: is_debian

- name: centos | update yum packages
  import_tasks: yum.yaml
  when: is_centos

- name: update oh my zsh for user
  ignore_errors: yes
  become: no
  shell: cd ~/.oh-my-zsh && git pull
  args:
    executable: /bin/bash

- name: update oh my zsh for root
  ignore_errors: yes
  become: yes
  shell: cd ~/.oh-my-zsh && git pull
  args:
    executable: /bin/bash
