---

- name: centos | update yum packages
  dnf:
    name: "*"
    state: latest
  vars:
    ansible_python_interpreter: "{{ '/usr/libexec/platform-python' if is_centos else '/usr/bin/python3' }}" # remove when migrated away from centos_7
