---

- name: centos | install ansible postgresql dependencies
  dnf:
    name:
    - postgresql-devel
    - python3-psycopg2
    state: latest
  vars:
    ansible_python_interpreter: "{{ '/usr/libexec/platform-python' if is_centos else '/usr/bin/python3' }}" # remove when migrated away from centos_7
