---

- name: Create user {{ config_user['name'] }}
  become: yes
  user:
    name: "{{ config_user['name'] }}"
    shell: /bin/bash
    createhome: yes
    groups: adm,dialout,cdrom,sudo,audio,video,plugdev,games,users,input,netdev,gpio,i2c,spi
    uid: "{{ config_user['uid'] }}"

- name: Add {{ config_user['name'] }} to sudoers
  lineinfile:
    dest: /etc/sudoers
    regexp: "^{{ config_user['name'] }}"
    line: "{{ config_user['name'] }} ALL=(ALL) NOPASSWD: ALL"
    state: present
    validate: 'visudo -cf %s'

- name: Add ssh keys to {{ config_user['name'] }}
  become: yes
  authorized_key:
    user: "{{ config_user['name'] }}"
    key: "{{ config_user['path_to_ssh_keys'] }}"
