---

- name: create env
  copy:
    src: .env
    dest: /etc/dokuwiki.env
    force: no
    group: root
    owner: root
    mode: 0755

- name: create volumes
  docker_volume:
    name: "{{ item.name }}"
    driver_options:
      type: nfs
      device: ":/{{ item.mount }}"
      o: "addr={{ nfs_host }},vers=4,tcp,rw,port=2049"
  with_items:
  - name: conf
    mount: "{{ conf_mount }}"

- name: start container
  docker_container:
    name: dokuwiki
    image: bitnami/dokuwiki:latest
    restart_policy: unless-stopped
    env_file: /etc/dokuwiki.env
    ports:
    - 80:80
    - 443:443
    volumes:
    - conf:/bitnami
