---
- name: centos | Open grafana services
  ansible.builtin.include_role:
    name: firewalld
  vars:
    firewalld_rule_name: grafana
    firewalld_ports:
      - name: grafana
        port: 3000/tcp

- name: centos | Open prometheus services
  ansible.builtin.include_role:
    name: firewalld
  vars:
    firewalld_rule_name: prometheus
    firewalld_ports:
      - name: prometheus
        port: 9090/tcp

- name: centos | Open speedtest services
  ansible.builtin.include_role:
    name: firewalld
  vars:
    firewalld_rule_name: speedtest
    firewalld_ports:
      - name: speedtest
        port: 9469/tcp

- name: centos | Open influxdb services
  ansible.builtin.include_role:
    name: firewalld
  vars:
    firewalld_rule_name: influxdb
    firewalld_ports:
      - name: http
        port: 8086/tcp
      - name: collectd
        port: 25826/udp
      - name: collectd
        port: 8089/udp

- name: centos | Open powerwall services
  ansible.builtin.include_role:
    name: firewalld
  vars:
    firewalld_rule_name: powerwall
    firewalld_ports:
      - name: pypowerwall
        port: 8675/tcp
      - name: weather411
        port: 8676/tcp
