---

- name: centos | install packages
  import_tasks: centos.yaml
  when: is_centos

- name: create nfs mount path dir
  file:
    path: "{{ item.client }}"
    state: directory
  with_items:
  - "{{ nfs_mount_paths }}"

- name: auto mount nfs share
  lineinfile:
    dest: /etc/fstab
    regexp: "{{ nfs.host }}:{{ item.host }} {{ item.client }} nfs4 defaults,proto=tcp,port=2049,rw 0 0"
    line: "{{ nfs.host }}:{{ item.host }} {{ item.client }} nfs4 defaults,proto=tcp,port=2049,rw 0 0"
    state: present
    insertbefore: "exit 0"
  with_items:
  - "{{ nfs_mount_paths }}"
  register: fstab

- name: reboot
  reboot:
    reboot_timeout: 60
  when: fstab is changed
