---

- name: create volumes
  docker_volume:
    name: "radarr_{{ item.name }}"
    driver_options:
      type: nfs
      device: ":/{{ item.mount }}"
      o: "addr={{ nfs_host }},vers=4,tcp,rw,port=2049"
  with_items:
  - name: conf
    mount: "{{ conf_mount }}"
  - name: downloads
    mount: "{{ downloads_mount }}"
  - name: movies
    mount: "{{ movies_mount }}"

- name: start container
  docker_container:
    name: radarr
    image: linuxserver/radarr:latest
    restart_policy: unless-stopped
    network_mode: host
    env:
      TZ: America/Los_Angeles
      PUID: "{{ radarr_docker_user_id | string }}"
      PGID: "0"
    ports:
    - 7878:7878
    volumes:
    - radarr_conf:/config
    - radarr_downloads:/downloads
    - radarr_movies:/movies
