---

- name: ping to verify current user
  action: ping
  ignore_unreachable: true
  ignore_errors: true
  register: ping

- name: clear host errors
  meta: clear_host_errors
  ignore_unreachable: true
  ignore_errors: true

- name: swap ansible_user to ipa.user
  block:
  - name: "set ansible_user ({{ ansible_user }}) to ipa.user ({{ global.ipa.user }})"
    set_fact:
      ansible_user: "{{ global.ipa.user }}"

  - name: ping to verify current user
    action: ping
  when: (is_freeipa) and (ping.failed | d(ping.unreachable) | d(false))
