---
- name: Ping to verify current user
  ansible.builtin.ping:
  ignore_unreachable: true
  ignore_errors: true
  register: ping

- name: Clear host errors
  ansible.builtin.meta: clear_host_errors
  ignore_unreachable: true
  ignore_errors: true

- name: Swap ansible_user to ipa.user
  when: (is_freeipa) and (ping.failed | d(ping.unreachable) | d(false))
  block:
    - name: "Set ansible_user ({{ ansible_user }}) to ipa.user ({{ global.ipa.user }})"
      ansible.builtin.set_fact:
        ansible_user: "{{ global.ipa.user }}"

    - name: Ping to verify current user
      ansible.builtin.ping:
