---
- name: set inventory facts
  import_tasks: facts/inventory.yaml

- name: "verify ansible_user ({{ ansible_user }}) user"
  import_tasks: ipa.yaml

- name: gather facts from all hosts in play
  setup:

- name: set system facts
  import_tasks: facts/system.yaml

- name: update hostname
  become: true
  command: "hostnamectl set-hostname {{ ansible_host }}"
  when: is_rpi == 'true'
