---

- name: centos | unregister spacewalk clients
  rhn_register:
    state: absent
    username: "{{ spacewalk.hostname }}"
    password: "{{ spacewalk.password }}"
  ignore_errors: yes
  when: sync and is_centos
