---

- name: install zsh
  yum:
    name: zsh
    state: latest
  when: ansible_os_family == "RedHat"

- name: install zsh
  yum:
    name: zsh
    state: latest
  when: ansible_os_family == "Debian"
