---

- name: reboot
  shell: "sleep 1 && shutdown -r now +1"
  async: 1
  poll: 0
  notify:
    - wait for reboot

- name: wait for reboot
  wait_for_connection:
    delay: "{{ reboot_min_wait_time }}"
    timeout: "{{ reboot_max_wait_time }}"
