- name: create network
  docker_network:
    name: mysql

- name: create service dirs
  file:
    group: nobody
    mode: "0777"
    owner: nobody
    path: "{{ item.path }}"
    state: directory
  with_items:
    - path: /opt/mysql

- name: start mysql container
  become: true
  docker_container:
    env:
      MYSQL_ROOT_PASSWORD: "{{ global.mysql.password }}"
    image: mysql:8.2.0
    name: mysql
    networks:
      - name: mysql
    ports:
      - 3306:3306
    restart_policy: always
    volumes:
      - /opt/mysql:/var/lib/mysql

- name: start exporter container
  become: true
  docker_container:
    command:
      - "--mysqld.username=root:{{ global.mysql.password }}"
      - "--mysqld.address=mysql:3306"
    image: prom/mysqld-exporter:v0.15.1
    name: mysql-metrics
    networks:
      - name: mysql
    ports:
      - 9104:9104
    restart_policy: always
