---

- name: set server usage facts
  set_fact:
    is_bastion: "{{ inventory_hostname == 'bastion' }}"
    is_docker: "{{ 'docker' in group_names }}"
    is_freeipa_server: "{{ 'ipaserver' in group_names }}"
    is_freeipa_client: "{{ 'ipaclients' in group_names }}"
    is_kubernetes: "{{ 'kubernetes' in group_names }}"
    is_server: "{{ 'servers' in group_names }}"
    is_spacewalk_client: "{{ 'spacewalkclients' in group_names }}"
    is_spacewalk_server: "{{ 'spacewalkserver' in group_names }}"
    is_vm_workstation: "{{ 'vmworkstations' in group_names }}"
    is_physical_workstation: "{{ 'physicalworkstations' in group_names }}"
    is_workstation: "{{ 'workstations' in group_names }}"

- name: set is_owned fact
  set_fact:
    is_internal: "{{ is_freeipa_server or is_freeipa_client or is_spacewalk_server or is_spacewalk_client }}"

- name: set system runner facts
  set_fact:
    run_bastion_setup: "{{ setup_bastion | default('false') | bool }}"
    run_rdp_setup: "{{ setup_rdp | default('false') | bool }}"
    run_postgresql_install: "{{ install_postgresql | default('false') | bool }}"
