---

- name: set server usage facts
  set_fact:
    is_bastion: "{{ inventory_hostname == 'bastion' }}"
    is_docker: "{{ 'docker' in group_names }}"
    is_freeipa_server: "{{ 'ipaserver' in group_names }}"
    is_freeipa_replica: "{{ 'ipareplicas' in group_names }}"
    is_freeipa_client: "{{ 'ipaclients' in group_names }}"
    is_kubernetes: "{{ 'kubernetes' in group_names }}"
    is_server: "{{ 'servers' in group_names }}"
    is_vm_workstation: "{{ 'vmworkstations' in group_names }}"
    is_physical_workstation: "{{ 'physicalworkstations' in group_names }}"
    is_workstation: "{{ 'workstations' in group_names }}"

- name: set is_freeipa fact
  set_fact:
    is_freeipa: "{{ is_freeipa_server or is_freeipa_replica or is_freeipa_client }}"
