---

- name: install nfs common
  yum:
    name: nfs-utils
    state: present

- name: create nfs mount path dir
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - "{{ nfs_mount_paths }}"

- name: auto mount nfs share
  lineinfile:
    dest: /etc/fstab
    regexp: "{{ item }}"
    line: "{{ item }}"
    state: present
    insertbefore: "exit 0"
  with_items:
  - "{{ nfs_mount_cmds }}"
  notify: reboot
