---

- name: create volumes
  docker_volume:
    name: "transmission_{{ item.name }}"
    driver_options:
      type: nfs
      device: ":/{{ item.mount }}"
      o: "addr={{ nfs_host }},vers=4,tcp,rw,port=2049"
  with_items:
  - name: conf
    mount: "{{ conf_mount }}"
  - name: downloads
    mount: "{{ downloads_mount }}"

- name: start container
  docker_container:
    name: transmission
    image: linuxserver/transmission:latest
    restart_policy: unless-stopped
    network_mode: host
    env:
      TZ: America/Los_Angeles
      PUID: "{{ radarr_docker_user_id | string }}"
      PGID: "0"
    ports:
    - 9091:9091
    - 51413:51413
    - 51413:51413/udp
    volumes:
    - transmission_conf:/config
    - transmission_downloads:/downloads
