---

- name: "{{ name }} | enable firewalld port (permanant)"
  firewalld:
    zone: public
    state: "{{ item.state | default('enabled') }}"
    port: "{{ item.port }}"
    permanent: yes

- name: "{{ name }} | enable firewalld port (not permanant)"
  firewalld:
    zone: public
    state: "{{ item.state | default('enabled') }}"
    port: "{{ item.port }}"
    permanent: no
  with_items: "{{ ports }}"
  notify: enable firewalld
