---

- name: "{{ item.name }} | enable firewalld port"
  firewalld:
    zone: public
    state: "{{ item.state | default('enabled') }}"
    port: "{{ item.port }}"
    permanent: "{{ permanent }}"
  loop:
  - yes
  - no
  loop_control:
    loop_var: permanent
  notify: enable firewalld
