- name: "{{ name }} | enable firewalld service (permanant)"
  firewalld:
    zone: public
    state: "{{ item.state | default('enabled') }}"
    service: "{{ item.service }}"
    permanent: yes
  with_items: "{{ services }}"
  notify: enable firewalld

- name: "{{ name }} | enable firewalld service (not permanant)"
  firewalld:
    zone: public
    state: "{{ item.state | default('enabled') }}"
    service: "{{ item.service }}"
    permanent: no
  with_items: "{{ services }}"
  notify: enable firewalld
