- name: centos | install dnf and python
  become: true
  dnf:
    name:
      - dnf
      - python3.9
      - python3-dnf
      - python3-pip
      - python3
    state: latest

- name: centos | create python3 symlink
  become: true
  file:
    src: "/usr/bin/python3.9"
    dest: "/usr/bin/python3"
    state: link
    force: yes
    follow: yes
- name: centos | create python symlink
  become: true
  file:
    src: "/usr/bin/python3"
    dest: "/usr/bin/python"
    state: link
    force: yes
    follow: yes

- name: centos | install epel-release
  dnf:
    name:
      - epel-release
    state: latest

- name: centos | install dnf packages
  become: true
  dnf:
    name:
      - curl
      - git
      - glibc-common
      - nfs-utils
      - python3-libselinux
      - sshpass
      - tar
      - tmux
      - tree # display directory tree
      - vim
      - zsh
    state: latest

- name: centos | install dnf packages
  become: true
  dnf:
    name:
      - util-linux-user
    state: latest
  when: is_centos

- name: centos | cleanup
  block:
    - name: centos | remove tools
      dnf:
        name:
          - collectd-rrdtool
          - subscription-manager
        state: absent
