---

- name: centos | install dnf using yum and python2
  block:
  - name: centos | create python3 symlink
    become: yes
    file:
      src: "/usr/bin/python3"
      dest: "/usr/bin/python"
      state: link
      force: yes

  - name: centos | install dnf and python3
    become: yes
    dnf:
      name:
      - dnf
      - python3
      state: latest
    when: is_centos_8

- name: centos | install dnf packages
  become: yes
  dnf:
    name:
    - nfs-utils
    - python3-libselinux
    - curl
    - git
    - sshpass
    - tar
    - tmux
    - tree        # display directory tree
    - vim
    - zsh
    state: latest
  vars:
    ansible_python_interpreter: "{{ '/usr/libexec/platform-python' if is_centos else '/usr/bin/python3' }}" # remove when migrated away from centos_7

- name: centos8 | install dnf packages
  become: yes
  dnf:
    name:
    - util-linux-user
    state: latest
  vars:
    ansible_python_interpreter: "{{ '/usr/libexec/platform-python' if is_centos else '/usr/bin/python3' }}" # remove when migrated away from centos_7
  when: is_centos_8

- name: centos | install pip packages
  block:
  - name: centos | install pip
    become: yes
    dnf:
      name:
      - python3-pip
      state: latest
    vars:
      ansible_python_interpreter: "{{ '/usr/libexec/platform-python' if is_centos else '/usr/bin/python3' }}" # remove when migrated away from centos_7

  - name: centos | create pip3 symlink
    become: yes
    file:
      src: "/usr/bin/pip3.6"
      dest: "{{ item }}"
      state: link
      force: yes
    with_items:
    - /usr/bin/pip3
    - /usr/bin/pip

- name: centos | cleanup rrd cache
  block:
  - name: centos | remove collectd rrdtool
    dnf:
      name:
      - collectd-rrdtool
      state: absent
    vars:
      ansible_python_interpreter: "{{ '/usr/libexec/platform-python' if is_centos else '/usr/bin/python3' }}" # remove when migrated away from centos_7

  - name: delete rrd
    file:
      state: absent
      path: /var/lib/collectd/rrd
      force: yes
    ignore_errors: yes
