---

- name: centos | install dnf using yum and python2
  block:
  - name: centos | install dnf and python3
    become: true
    dnf:
      name:
      - dnf
      - python3
      state: latest
    when: is_centos_8

  - name: centos | create python3 symlink
    become: true
    file:
      src: "/usr/bin/python3"
      dest: "/usr/bin/python"
      state: link
      force: yes
      follow: yes

- name: centos | install epel-release
  dnf:
    name:
    - epel-release
    state: latest

- name: centos | install dnf packages
  become: true
  dnf:
    name:
    - curl
    - git
    - nfs-utils
    - python3-libselinux
    - sshpass
    - tar
    - tmux
    - tree        # display directory tree
    - vim
    - zsh
    state: latest

- name: centos8 | install dnf packages
  become: true
  dnf:
    name:
    - util-linux-user
    state: latest
  when: is_centos_8

- name: centos | install pip packages
  block:
  - name: centos | install pip
    become: true
    dnf:
      name:
      - python3-pip
      state: latest

  - name: centos | create pip3 symlink
    become: true
    file:
      src: "/usr/bin/pip3.6"
      dest: "{{ item }}"
      state: link
      force: yes
    with_items:
    - /usr/bin/pip3
    - /usr/bin/pip

- name: centos | cleanup rrd cache
  block:
  - name: centos | remove collectd rrdtool
    dnf:
      name:
      - collectd-rrdtool
      state: absent

  - name: delete rrd
    file:
      state: absent
      path: /var/lib/collectd/rrd
      force: yes
    ignore_errors: yes
