- name: debian | upgrade apt packages
  become: true
  apt:
    update_cache: yes

- name: debian | install apt packages
  become: true
  apt:
    name:
      - curl
      - git
      - nfs-common
      - python3
      - python3-pip
      - sshpass
      - tar
      - tmux
      - tree # display directory tree
      - vim
      - zsh
    state: latest
