---

- name: debian | upgrade apt packages
  become: yes
  apt:
    update_cache: yes

- name: debian | install apt packages
  become: yes
  apt:
    name:
    - nfs-common
    - python3
    - python3-pip
    - curl
    - git
    - sshpass
    - tar
    - tmux
    - tree        # display directory tree
    - vim
    - zsh
    state: latest
