---

- name: centos | install epel-release
  yum:
    name:
    - epel-release
    state: latest
  when: not is_spacewalk_client and is_centos

- name: centos | install yum packages
  become: yes
  yum:
    name:
    - nfs-utils
    - sshpass
    - python3-pip
    - python2-pip
    - vim
    state: latest
  when: is_centos

- name: debian | install apt packages
  apt:
    name:
    - nfs-common
    - sshpass
    - python3-pip
    - tree        # display directory tree
    - vim
    state: latest
  when: is_debian
