- name: centos | install packages
  import_tasks: centos.yaml
  when: is_centos

- name: debian | install packages
  import_tasks: debian.yaml
  when: is_debian

- name: delete rrd
  file:
    state: absent
    path: /var/lib/collectd/rrd
    force: true
  ignore_errors: true

- name: python | update pip
  command: python -m ensurepip --upgrade
- name: python | install modules
  command: pip install packaging

# fails for some?
- name: pip | install setuptools
  become: false
  pip:
    name:
      - setuptools
      - setuptools_rust
      - wheel
    state: latest
    extra_args: --user
  ignore_errors: true

- name: pip | install deps
  become: false
  pip:
    name:
      - argparse-manpage
      - dnspython
      - docker
      - libs
      - neovim
      # investigate why these are needed
      - PGPy
      # - pyOpenSSL investigate this.., fails on rpi
      - pytest
    # - thefuck remove
    extra_args: --user

- name: install neovim
  block:
    - name: download neovim install script
      become: false
      get_url:
        # new fix to remove glibc requirement
        url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
        dest: /tmp/nvim.appimage
        mode: +x
        force: true

    - name: run neovim install script
      become: false
      shell: cd /tmp && /tmp/nvim.appimage --appimage-extract
      args:
        executable: /bin/bash

    # todo may need to move to /usr/local/bin instead or 744 permissions
    - name: move neovim to /opt
      become: true
      shell: rm -rf /opt/squashfs-root && mv /tmp/squashfs-root /opt
      args:
        executable: /bin/bash

    - name: create neovim link
      become: true
      file:
        src: /opt/squashfs-root/AppRun
        dest: /usr/bin/nvim
        state: link
        force: yes

- name: install packages for multiple users
  include_tasks: multiple_users.yaml
  with_items: "{{ ansible_users }}"
