---

- name: download service
  get_url:
    url: https://dl.eff.org/certbot-auto
    dest: /usr/local/bin/certbot-auto

- name: change service ownership
  file:
    dest: /usr/local/bin/certbot-auto
    owner: root
    mode: 0755
