---

- name: centos | install rdp packages
  yum:
    name:
    - tigervnc-server
    - xrdp
    state: latest

- name: centos | open firewalld ports
  include_tasks: firewalld.yaml
  when: is_centos
