---

- name: restart ssh
  service:
    name: sshd
    state: restarted

- name: enable fail2ban
  service:
    name: fail2ban
    state: started
    enabled: yes

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted
