---
- name: restart ssh | Force lookup ipa user id
  ansible.builtin.command: "id {{ global.ipa.user }}"
  when: is_freeipa_client
  listen: restart ssh

- name: restart ssh | Reboot to sync freeipa login
  ansible.builtin.include_tasks: ../roles/global/tasks/reboot.yaml # include required to read vars
  when: is_freeipa_client and (ansible_user != global.ipa.user)
  listen: restart ssh

- name: Restart ssh
  ansible.builtin.service:
    name: sshd
    state: restarted
  listen: restart ssh

- name: Swap ansible_user to ipa.user
  ansible.builtin.include_tasks: ../roles/global/tasks/ipa.yaml # include required to read vars
  when: is_freeipa_client
  listen:
    - enable fail2ban
    - restart fail2ban

- name: Enable fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
  listen: enable fail2ban

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
  listen: restart fail2ban
