---

- name: restart ssh | force lookup ipa user id
  command: "id {{ global.ipa.user }}"
  when: is_freeipa_client
  listen: restart ssh

- name: restart ssh | reboot to sync freeipa login
  include_tasks: ../roles/global/tasks/reboot.yaml # include required to read vars
  when: is_freeipa_client and (ansible_user != global.ipa.user)
  listen: restart ssh

- name: restart ssh
  service:
    name: sshd
    state: restarted
  listen: restart ssh

- name: swap ansible_user to ipa.user
  include_tasks: ../roles/global/tasks/ipa.yaml # include required to read vars
  when: is_freeipa_client
  listen:
  - enable fail2ban
  - restart fail2ban

- name: enable fail2ban
  service:
    name: fail2ban
    state: started
    enabled: yes
  listen: enable fail2ban

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted
  listen: restart fail2ban
