- name: centos | open flaresolverr services
  include_role:
    name: services/firewalld
  vars:
    firewalld_rule_name: flaresolverr
    firewalld_ports:
      - name: flaresolverr
        port: 8191/tcp

- name: centos | open jackett services
  include_role:
    name: services/firewalld
  vars:
    firewalld_rule_name: jackett
    firewalld_ports:
      - name: jackett
        port: 9117/tcp

- name: centos | open transmission services
  include_role:
    name: services/firewalld
  vars:
    firewalld_rule_name: transmission
    firewalld_ports:
      - name: transmission
        port: 9091/tcp
      - name: transmission-vpn
        port: 54949/tcp
      - name: transmission-vpn-udp
        port: 54949/tcp

- name: centos | open sabnzbd services
  include_role:
    name: services/firewalld
  vars:
    firewalld_rule_name: sabnzbd
    firewalld_ports:
      - name: sabnzbd
        port: 8080/tcp

- name: centos | open radarr services
  include_role:
    name: services/firewalld
  vars:
    firewalld_rule_name: radarr
    firewalld_ports:
      - name: radarr
        port: 7878/tcp

- name: centos | open sonarr services
  include_role:
    name: services/firewalld
  vars:
    firewalld_rule_name: sonarr
    firewalld_ports:
      - name: sonarr
        port: 8989/tcp

- name: centos | open readarr services
  include_role:
    name: services/firewalld
  vars:
    firewalld_rule_name: readarr
    firewalld_ports:
      - name: readarr
        port: 8787/tcp

- name: centos | open calibre-server services
  include_role:
    name: services/firewalld
  vars:
    firewalld_rule_name: calibre-server
    firewalld_ports:
      - name: calibre-server
        port: 7070/tcp
      - name: calibre-server
        port: 8081/tcp
