- name: mvn | set facts
  set_fact:
    install_path: "/opt/mvn-{{ global.version.mvn }}"

- name: mvn | create install dir
  become: true
  file:
    path: "{{ install_path }}"
    state: directory

- name: mvn | download and untar
  become: true
  unarchive:
    remote_src: yes
    src: "https://mirror.jframeworks.com/apache/maven/maven-3/{{ global.version.mvn }}/binaries/apache-maven-{{ global.version.mvn }}-bin.tar.gz"
    dest: "{{ install_path }}"
    extra_opts:
      - --strip-components=1

- name: mvn | register bin files
  become: true
  find:
    paths:
      - "{{ install_path }}/bin"
    file_type: file
    use_regex: yes
    patterns:
      - ^[^\.]+$
  register: find_maven

- name: mvn | create symlinks
  become: true
  file:
    src: "{{ item.path }}"
    dest: "/usr/local/bin/{{ item.path | basename }}"
    state: link
    force: yes
  with_items: "{{ find_maven.files }}"

- name: nvm | install and use
  become: false
  shell: "source {{ ansible_env['HOME'] }}/.zshrc && nvm install {{ global.version.node }} && nvm use {{ global.version.node }}"
  args:
    executable: /bin/zsh
