---
- name: Install duo packages
  ansible.builtin.dnf:
    name:
      - duo_unix
    state: present

- name: Configure duo settings
  ansible.builtin.lineinfile:
    dest: /etc/duo/login_duo.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - {regexp: ^ikey =, line: "ikey = {{ bastion_duo_ikey }}"}
    - {regexp: ^skey =, line: "skey = {{ bastion_duo_skey }}"}
    - {regexp: ^host =, line: "host = {{ bastion_duo_host }}"}
