---

- name: ledger | download install image
  become: true
  get_url:
    url: https://download-live.ledger.com/releases/latest/download/linux
    dest: /opt/ledger
    mode: +x

- name: ledger | create shortcut
  become: true
  file:
    src: /opt/ledger
    dest: /usr/local/bin/ledger
    state: link

- name: ledger | create shortcut
  copy:
    dest: ~/.local/share/applications/ledger.desktop
    content: |
      [Desktop Entry]
      Type=Application
      Terminal=false
      Name=Ledger
      Exec=ledger
