---

- name: ledger | download install image
  become: yes
  get_url:
    url: https://download-live.ledger.com/releases/latest/download/linux
    dest: /opt/ledger
    mode: +x

- name: ledger | create shortcut
  become: yes
  file:
    src: /opt/ledger
    dest: /usr/local/bin/ledger
    state: link

- name: ledger | create shortcut
  copy:
    dest: ~/.local/share/applications/ledger.desktop
    content: |
      [Desktop Entry]
      Type=Application
      Terminal=false
      Name=Ledger
      Exec=ledger

- name: arduino | install
  become: yes
  block:
  - name: arduino | download and untar
    unarchive:
      remote_src: yes
      src: https://downloads.arduino.cc/arduino-1.8.13-linux64.tar.xz
      dest: /opt

  - name: arduino | install
    become: yes
    command: /bin/sh /opt/arduino-1.8.13/install.sh
