- name: centos | install rdp packages
  dnf:
    name:
      - tigervnc-server
      - xrdp
    state: latest

- name: centos | open rdp ports
  include_role:
    name: services/firewalld/tasks
  vars:
    name: rdp
    ports:
      - name: xrdp
        port: 3389/tcp
