---

- name: install neovim
  block:
  - name: download neovim install script
    become: no
    get_url:
      url: https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
      dest: /tmp/nvim.appimage
      mode: +x

  - name: run neovim install script
    become: no
    shell: cd /tmp && /tmp/nvim.appimage --appimage-extract
    args:
      executable: /bin/bash

  - name: move neovim to /opt
    become: yes
    shell: rm -rf /opt/squashfs-root && mv /tmp/squashfs-root /opt
    args:
      executable: /bin/bash

  - name: create neovim link
    become: yes
    file:
      src: /opt/squashfs-root/AppRun
      dest: /usr/bin/nvim
      state: link
      force: yes

- name: install packages
  yum:
    name:
    # - python3-neovim
    - zsh
    - git
    - curl
    state: latest

- name: install pip dependencies
  yum:
    name:
    - gcc
    - python2-devel
    - python3-devel
    - python3-libs
    - python3-pip
    - python3-setuptools
    state: latest

- name: update pip setuptools
  become: no
  pip: 
    name: setuptools
    state: latest

- name: pip install thefuck for user
  become: no
  pip:
    name: thefuck
    executable: pip3
