---

- name: install packages
  apt:
    name:
    - neovim
    - python3-neovim
    - zsh
    state: latest

- name: pip install thefuck
  become: yes
  pip:
    name: thefuck
    executable: pip3
    state: latest
