---

- name: centos | open bastion ports
  include_tasks: ../roles/services/firewalld/tasks/port.yaml
  loop:
  - name: bastion sish ssh server
    port: "{{ sish.sshAddress }}/tcp"
  - name: bastion sish http
    port: "{{ sish.httpAddress }}/tcp"
  - name: bastion sish https
    port: "{{ sish.httpsAddress }}/tcp"
  - name: bastion sish ssh client
    port: "9222/tcp"
