---

- name: configure tunnel
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
  - { regexp: "^PermitTunnel", line: "PermitTunnel no" }
  - { regexp: "^AllowTcpForwarding", line: "AllowTcpForwarding no" }
  - { regexp: "^ChallengeResponseAuthentication no", line: "ChallengeResponseAuthentication yes" }
  notify: restart ssh

- name: allow access from internal addresses
  blockinfile:
    dest: /etc/ssh/sshd_config
    marker: "# {mark}-bastion-internal-allow"
    block: |
      Match Address *,!192.168.*.1,192.168.*.*,10.0.*.*
        AllowTcpForwarding yes
  notify: restart ssh

- name: require duo authentication for bastion user from gateway
  blockinfile:
    dest: /etc/ssh/sshd_config
    marker: "# {mark}-bastion-gateway-auth"
    block: |
      Match User {{ global.bastion.user }} Address 192.168.*.1
        ForceCommand /usr/sbin/login_duo
        AllowTcpForwarding yes
  notify: restart ssh

- name: block access to non bastion users from gateway
  blockinfile:
    dest: /etc/ssh/sshd_config
    marker: "# {mark}-bastion-gateway-block"
    block: |
      Match User *,!{{ global.bastion.user }} Address 192.168.*.1
        ForceCommand /bin/false
  notify: restart ssh
