---

- name: set ssh key for {{ ansible_user }}
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ server_ssh_keys_url }}"
    state: present

- name: disable ssh password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: "^PasswordAuthentication", line: "PasswordAuthentication no" }
  notify: restart ssh

- name: install fail2ban
  yum:
    name:
    - fail2ban
    - fail2ban-systemd
    state: present
  notify: ensure fail2ban is running
  when: ansible_os_family == "RedHat"

- name: fail2ban sshban jail
  blockinfile:
    dest: /etc/fail2ban/jail.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK #"
    block: |
      [sshban]
      enabled   = true
      port      = ssh
      logpath   = %(sshd_log)s
      banaction = iptables-allports
      maxretry  = 10
      bantime   = 86400
      filter    = sshd
