---

- name: mount conf dir
  mount:
    path: /tmp/mnt
    src: "{{ nfs_host }}:{{ conf_mount }}"
    fstype: nfs4
    opts: defaults,proto=tcp,port=2049,rw
    state: mounted

- name: prometheus conf
  template:
    src: conf.j2
    dest: /tmp/mnt/prometheus.yml

- name: unmount conf dir
  mount:
    path: /tmp/mnt
    state: unmounted

- name: create volumes
  docker_volume:
    name: "{{ item.name }}"
    driver_options:
      type: nfs
      device: ":/{{ item.mount }}"
      o: "addr={{ nfs_host }},vers=4,tcp,rw,port=2049"
  with_items:
  - name: conf
    mount: "{{ conf_mount }}"
  - name: data
    mount: "{{ data_mount }}"

- name: start container
  docker_container:
    name: prometheus
    image: prom/prometheus:latest
    restart_policy: unless-stopped
    user: "{{ prometheus_docker_user_id }}:0"
    command:
    - --config.file="/etc/prometheus/prometheus.yml"
    - --storage.tsdb.path="/data/prometheus"
    ports:
    - 80:9090
    volumes:
    - conf:/etc/prometheus
    - data:/data/prometheus

- name: restart container
  docker_container:
    name: prometheus
    state: started
    restart: yes
