---

- name: create volumes
  docker_volume:
    name: "{{ item.name }}"
    driver_options:
      type: nfs
      device: ":/{{ item.mount }}"
      o: "addr={{ nfs_host }},vers=4,tcp,rw,port=2049"
  with_items:
  - name: conf
    mount: "{{ conf_mount }}/journal"
  - name: content
    mount: "{{ conf_mount }}/content"
  - name: plugin
    mount: "{{ conf_mount }}/plugin"

- name: start container
  docker_container:
    name: graylog
    image: graylog/graylog:3.1
    restart_policy: unless-stopped
    # user: "{{ graylog_docker_user_id }}:0"
    env:
      GRAYLOG_HTTP_EXTERNAL_URI: "http://{{ ansible_host }}:9000/"
      GRAYLOG_MONGODB_URI: "{{ graylog_mongo_uri }}"
      GRAYLOG_ELASTICSEARCH_HOSTS: "{{ graylog_es_hosts }}"
    ports:
    - 9000:9000
    # - 12201:12201
    # - 12201:12201/udp
    - 514:514/udp
    - 515:515/udp
    volumes:
    - conf:/usr/share/graylog/data/journal
    - content:/usr/share/graylog/data/content
    - plugin:/usr/share/graylog/plugin
