---
- name: centos | Open bastion ports
  ansible.builtin.include_role:
    name: services/firewalld
  vars:
    firewalld_rule_name: bastion
    firewalld_ports:
      - name: bastion sish ssh server
        port: "{{ global.sish.sshPort }}/tcp"
      - name: bastion sish http
        port: "{{ global.sish.forwardingPorts.http }}/tcp"
      - name: bastion sish https
        port: "{{ global.sish.forwardingPorts.https }}/tcp"

- name: Create tcp port var
  ansible.builtin.set_fact:
    tcpPorts: "{{ tcpPorts | default([]) + [{'name': 'tcp forwarding port', 'port': '{{ item }}/tcp'}] }}"
  with_items: "{{ global.sish.forwardingPorts.tcp }}"

- name: centos | Open bastion ports
  ansible.builtin.include_role:
    name: services/firewalld
  vars:
    firewalld_rule_name: bastion
    firewalld_ports: "{{ tcpPorts }}"
