- name: set sish docker ports
  set_fact:
    ports: "['{{ global.sish.sshPort }}:{{ global.sish.sshPort }}', '{{ global.sish.forwardingPorts.http }}:{{ global.sish.forwardingPorts.http }}', '{{ global.sish.forwardingPorts.https }}:{{ global.sish.forwardingPorts.https }}']"

- name: append tcp ports
  set_fact:
    ports: "{{ ports }} + ['{{ item }}:{{ item }}']"
  with_items: "{{ global.sish.forwardingPorts.tcp }}"

- name: launch sish container
  become: true
  docker_container:
    name: sish
    image: "antoniomika/sish:{{ global.sish.tag }}"
    restart_policy: unless-stopped
    hostname: "{{ inventory_hostname }}"
    ports: "{{ ports }}"
    command: >-
      --ssh-address=:{{ global.sish.sshPort }}
      --http-address=:{{ global.sish.forwardingPorts.http }}
      --https-address=:{{ global.sish.forwardingPorts.https }}
      --https=true
      --https-certificate-directory=/ssl
      --https-ondemand-certificate=true
      --authentication=true
      --authentication-password=""
      --authentication-keys-directory=/pubkeys
      --private-key-location=/keys/ssh_key
      --private-key-passphrase={{ global.sish.privateKeyPassphrase }}
      --bind-random-ports=false
      --bind-random-subdomains=false
      --domain={{ global.sish.domain }}
      --idle-connection-timeout=600s
    volumes:
      - "~/sish/ssl:/ssl"
      - "~/sish/keys:/keys"
      - "~/sish/pubkeys:/pubkeys"

- name: centos | open firewalld ports
  import_tasks: firewalld.yaml
  when: is_centos
