- name: centos | find all yum repos
  find:
    paths:
      - /etc/yum.repos.d/
    patterns: "*.repo"
  register: repos

- name: centos | disable all yum repos
  lineinfile:
    dest: "{{ item.path }}"
    regexp: "^enabled=1"
    line: "enabled=0"
    state: present
  with_items: "{{ repos.files }}"
  notify: clean repos

- name: centos8 | disable additional repos
  yum_repository:
    name: "{{ item }}"
    state: absent
  with_items:
    - CentOS-8 - AppStream
    - CentOS-8 - Base
    - CentOS-8 - Extras
  when: is_centos_8
  notify: clean repos
