---

- name: configure keyboard
  block:
  - name: remap capslock to escape
    shell: gsettings set org.gnome.desktop.input-sources xkb-options "['caps:escape']"

  - name: disable emoji picker
    shell: gsettings set org.freedesktop.ibus.panel.emoji hotkey "@as []"

- name: configure settings
  block:
  - name: gnome autosave session
    dconf:
      key: /org/gnome/gnome-session/auto-save-session
      value: "'true'"

- name: pip install dependencies
  become: no
  pip:
    name:
      - decorator
      - psutil
    executable: pip3
    extra_args: --user

- name: set profile picture
  become: yes
  copy:
    src: files/profile.jpeg
    dest: "/var/lib/AccountsService/icons/{{ ansible_user }}"
    force: yes

- name: set wallpaper
  copy:
    src: files/wallpaper.png
    dest: "{{ ansible_env['HOME'] }}/.wallpaper.png"

- name: set gnome wallpaper
  dconf:
    key: /org/gnome/desktop/background/picture-uri
    value: "'file://{{ ansible_env['HOME'] }}/.wallpaper.png'"

- name: create gnome extension dir
  file:
    path: "{{ ansible_env['HOME'] }}/.local/share/gnome-shell/extensions"
    state: directory

- name: install and configure vlc
  block:
  - name: install vlc
    become: yes
    apt:
      name:
      - vlc    
      state: latest

  - name: set vlc as default video player
    become: yes
    replace:
      path: /usr/share/applications/defaults.list
      regexp: org\.gnome\.Totem\.desktop$
      replace: vlc.desktop

  - name: set vlc as only option in mime cache
    become: yes
    replace:
      path: /usr/share/applications/mimeinfo.cache
      regexp: org\.gnome\.Totem\.desktop;(vlc\.desktop;)?$
      replace: vlc.desktop;

- name: check if sound output extension exists
  stat:
    path: "{{ ansible_env['HOME'] }}/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net"
  register: sound_output

- name: install sound output extension
  block:
  - name: download sound output extension
    git:
      repo: https://github.com/kgshank/gse-sound-output-device-chooser.git
      dest: /tmp/gse-sound-output-device-chooser

  - name: move extension to gnome shell
    command: |
      mv \
      /tmp/gse-sound-output-device-chooser/sound-output-device-chooser@kgshank.net \
      {{ ansible_env['HOME'] }}/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net
  when: not sound_output.stat.exists

- name: enable sound output extension
  dconf:
    key: /org/gnome/shell/enabled-extensions
    value: "['sound-output-device-chooser@kgshank.net']"
