---
- name: Disable root login
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - {regexp: "^PermitRootLogin", line: "PermitRootLogin no"}
  notify: restart ssh

- name: Disable password authentication
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - {regexp: "^PasswordAuthentication", line: "PasswordAuthentication no"}
  when: is_freeipa
  notify: restart ssh

- name: Disable challenge response authentication
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - {regexp: "^ChallengeResponseAuthentication yes", line: "ChallengeResponseAuthentication no"}
  when: is_freeipa and not is_bastion
  notify: restart ssh

- name: Configure bastion host access
  when: (bastion_host | default('') | length > 0) and not is_bastion

  block:
    - name: Block access to non bastion user from bastion host
      ansible.builtin.blockinfile:
        dest: /etc/ssh/sshd_config
        marker: "# {mark}-block-bastion"
        block: |
          Match User *,!{{ bastion_user }} Address {{ bastion_host }}
            ForceCommand /bin/false
      when: is_freeipa and (bastion_user and bastion_host)
      notify: restart ssh

    - name: Block access from bastion host if not registered on freeipa
      ansible.builtin.blockinfile:
        dest: /etc/ssh/sshd_config
        marker: "# {mark}-block-bastion"
        block: |
          Match Address {{ bastion_host }}
            ForceCommand /bin/false
      when: not is_freeipa and bastion_host
      notify: restart ssh
- name: centos | Install fail2ban
  ansible.builtin.import_tasks: centos.yaml
  when: is_centos

- name: debian | Install fail2ban
  ansible.builtin.import_tasks: debian.yaml
  when: is_debian

- name: Configure fail2ban jail
  ansible.builtin.blockinfile:
    dest: /etc/fail2ban/jail.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK #"
    block: |
      [sshban]
      enabled   = true
      port      = ssh
      logpath   = %(sshd_log)s
      banaction = iptables-allports
      maxretry  = 10
      bantime   = 86400
      filter    = sshd
  notify: restart fail2ban
