---

- name: create volumes
  docker_volume:
    name: "{{ item.name }}"
    driver_options:
      type: nfs
      device: ":/{{ item.mount }}"
      o: "addr={{ nfs_host }},vers=4,tcp,rw,port=2049"
  with_items:
  - name: conf
    mount: "{{ conf_mount }}"
  - name: transcode
    mount: "{{ transcode_mount }}"
  - name: movies
    mount: "{{ movies_mount }}"
  - name: tv_shows
    mount: "{{ tv_shows_mount }}"

- name: start container
  docker_container:
    name: plex
    image: plexinc/pms-docker:plexpass
    restart_policy: unless-stopped
    hostname: "{{ inventory_hostname }}"
    network_mode: host
    env:
      TZ: America/Los_Angeles
      ADVERTISE_IP: "http://{{ plex_ip }}:32400/"
      PLEX_CLAIM: "{{ plex_claim }}"
      CHANGE_CONFIG_DIR_OWNERSHIP: "false"
      PLEX_UID: "{{ plex_docker_user_id | string }}"
      PLEX_GID: "0"
    ports:
    - 32400:32400/tcp
    - 3005:3005/tcp
    - 8324:8324/tcp
    - 32469:32469/tcp
    - 1900:1900/udp
    - 32410:32410/udp
    - 32412:32412/udp
    - 32413:32413/udp
    - 32414:32414/udp
    volumes:
    - conf:/config
    - transcode:/transcode
    - movies:/data/movies
    - tv_shows:/data/tv-shows
