---
# Let's Encrypt certificates via the Cloudflare DNS challenge.
- import_playbook: bootstrap.yml

- name: Configure acme certs
  hosts: acme
  gather_facts: false
  tags: acme
  vars:
    letsencrypt_production: true
    include_intermediate: false
  tasks:
    - name: Obtain certificates
      ansible.builtin.include_role:
        name: letsencrypt_cloudflare

    - name: Install certificates
      ansible.builtin.include_role:
        name: acme
