---

- name: configure influxdb
  hosts: influxdb
  become: yes
  roles:
  - name: firewalld
    ports:
    - 8086/tcp
    - 8088/tcp
    - 2003/tcp
    - 25826/udp
    - 8089/udp
    services: []
  - name: influxdb
    conf_mount: "{{ influxdb_docker_path }}"
    data_mount: "{{ influxdb_database_path }}"
    telegraf_db: telegraf
    proxmox_db: proxmox
