---
# ansible-playbook -i inventory/hosts playbooks/intialize.yaml

- name: Initializes the server
  hosts: all
  become: yes
  roles:
    - hostname
    - name: "update"
      tags: "update"
    - secure
  vars_files:
    - ../vars.yaml
