---
# Sonarr / Radarr / Jackett / SABnzbd / Transmission / Calibre.
- import_playbook: bootstrap.yml

- name: configure pirate
  hosts: pirate
  become: true
  gather_facts: false
  tags: pirate
  roles:
    - docker/pirate
