---

- name: configure pirate
  hosts: pirate
  become: yes
  roles:
  - name: firewalld
    ports:
    - 7878/tcp
    - 8989/tcp
    - 9091/tcp
    - 9117/tcp
    - 23848/tcp
    - 23848/udp
    - 51413/tcp
    - 51413/udp
    services: []
  - name: jackett
    conf_mount: "{{ jackett_docker_path }}"
  - name: radarr
    conf_mount: "{{ radarr_docker_path }}"
    downloads_mount: "{{ downloads_media_path }}"
    movies_mount: "{{ movies_media_path }}"
  - name: sonarr
    conf_mount: "{{ sonarr_docker_path }}"
    downloads_mount: "{{ downloads_media_path }}"
    tv_shows_mount: "{{ tv_shows_media_path }}"
  - name: transmission
    conf_mount: "{{ transmission_docker_path }}"
    downloads_mount: "{{ downloads_media_path }}"
