---

- name: configure postgres
  hosts: postgres
  become: yes
  roles:
  - name: firewalld
    ports:
    - 5432/tcp
    - 9187/tcp
    services: []
  - name: postgres
    data_mount: "{{ postgres_database_path }}"
