---

- name: set facts and ssh user
  hosts: all
  become: no
  gather_facts: no
  ignore_errors: true
  ignore_unreachable: true
  roles:
  - global
  tags: always

- name: install & update packages
  hosts: all
  become: yes
  tags: install-update
  roles:
  - name: packages/install
    tags: install
  - name: packages/update
    tags: update

- name: configure terminal
  hosts: all
  become: no
  tags: terminal
  roles:
  - terminal

- name: configure acme certs
  hosts: acme
  tags: acme
  vars:
  - letsencrypt_production: yes
  - include_intermediate: no
  tasks:
  - include_role:
      name: ansible-letsencrypt-cloudflare
  - include_role:
      name: services/acme

# - name: uninstall freeipa clients
#   become: yes
#   tags: freeipa-client-uninstall
#   import_playbook: ../ansible-freeipa/playbooks/uninstall-client.yml
#   vars:
#     ansible_python_interpreter: /usr/bin/python2

- name: configure freeipa server/replica
  become: yes
  hosts: ipaservers,ipareplicas
  tags: freeipa
  tasks:
  - name: update hostname
    command: "hostnamectl set-hostname {{ ansible_host }}"
  - include_role:
      name: services/freeipa/server

- name: install freeipa server
  become: yes
  hosts: ipaservers
  tags: freeipa-server
  tasks:
  - include_role:
      name: ipaserver

# manually append isrg root x1 let's encrypt cert and re-run ipa-certupdate (if using let's encrypt)
# https://yyhh.org/blog/2021/01/fix-freeipa-httpd-lets-encrypt-certificate-update/
- name: install freeipa replica
  become: yes
  hosts: ipareplicas
  tags: freeipa-replicas
  tasks:
  - include_role:
      name: ipareplica

# disable anonymous binds
# https://stomp.colorado.edu/blog/blog/2011/12/19/on-increasing-the-security-of-a-freeipa-server/
# sudo service ipa stop
# sudo vi /etc/dirsrv/slapd-DOMAIN-COM/dse.ldif
# Search for nsslapd-allow-anonymous-access and change on to rootdse
# sudo service ipa start
- name: configure freeipa server
  become: yes
  hosts: ipaservers,ipareplicas
  tags: freeipa-configure
  roles:
  - services/freeipa/server/configure

- name: register freeipa clients
  import_playbook: ../ansible-freeipa/playbooks/install-client.yml
  tags: freeipa-client

- name: configure servers group
  hosts: servers
  become: yes
  vars:
    sync: false # resets all configuration before re-applying
  tags: server
  roles:
  - services/ssh/setup
  - name: services/collectd
    tags: collectd

- name: configure docker group
  hosts: docker
  become: yes
  tags: docker
  roles:
  - name: services/docker
    when: not is_kubernetes
  - name: docker/metrics
    when: not is_workstation and not is_kubernetes

- name: configure kubernetes group
  hosts: kubernetes
  become: yes
  tags: kubernetes
  roles:
  - name: services/kubernetes
    vars:
      create_mnt_dirs: no
      dirs: []

- name: configure kubernetes partitions
  hosts: kube_node
  become: yes
  tags: kubernetes-partition
  roles:
  - name: services/partition

- name: configure workstations group
  hosts: workstations
  tags: workstations
  roles:
  - workstations
  - name: docker/syncthing
    tags: docker/syncthing

- name: configure bastion
  hosts: bastion
  become: yes
  pre_tasks:
  - fail:
      msg: bastion host and duo settings required
    when: global.bastion is undefined or not global.bastion.host or not global.bastion.duo or not global.bastion.duo.ikey or not global.bastion.duo.skey or not global.bastion.duo.host
  tags: bastion
  roles:
  - services/duo
  - services/ssh/bastion
  - name: docker/sish
    tags: docker/sish

- name: configure media
  hosts: media
  become: yes
  tags: media
  roles:
  - docker/media
