- name: set facts and ssh user
  hosts: all
  become: false
  gather_facts: false
  ignore_errors: true
  ignore_unreachable: true
  roles:
    - global
  tags: always

- name: install & update packages
  hosts: all
  become: true
  tags: install-update
  roles:
    - name: packages/install
      tags: install
    - name: packages/update
      tags: update

- name: configure terminal
  hosts: all
  become: false
  tags: terminal
  roles:
    - terminal

- name: configure acme certs
  hosts: acme
  tags: acme
  vars:
    - letsencrypt_production: yes
    - include_intermediate: no
  tasks:
    - include_role:
        name: ansible-letsencrypt-cloudflare
    - include_role:
        name: services/acme

- name: configure servers group
  hosts: servers
  become: true
  vars:
    sync: false # resets all configuration before re-applying
  tags: server
  roles:
    - services/ssh/setup
    - name: services/collectd
      tags: collectd

- name: configure docker group
  hosts: docker
  become: true
  tags: docker
  roles:
    - name: services/docker
      when: not is_kubernetes
    - name: docker/metrics
      when: not is_kubernetes

- name: configure kubernetes group
  hosts: kubernetes
  become: true
  tags: kubernetes
  roles:
    - name: services/kubernetes
      vars:
        create_mnt_dirs: no
        dirs: []

- name: configure kubernetes partitions
  hosts: kube_node
  become: true
  tags: kubernetes-partition
  roles:
  - name: services/partition
    when: not is_rpi

- name: configure workstations group
  hosts: workstations
  tags: workstations
  roles:
  - workstations

- name: configure bastion
  hosts: bastion
  become: true
  pre_tasks:
    - fail:
        msg: bastion host and duo settings required
      when: global.bastion is undefined or not global.bastion.host or not global.bastion.duo or not global.bastion.duo.ikey or not global.bastion.duo.skey or not global.bastion.duo.host
  tags: bastion
  roles:
    - services/duo
    - services/ssh/bastion
    - name: docker/sish
      tags: docker/sish

- name: configure auth
  hosts: auth
  become: true
  tags: auth
  roles:
    - docker/postgresql
    - docker/auth

- name: configure media
  hosts: media
  become: true
  tags: media
  roles:
    - docker/mysql
    - docker/postgresql
    - docker/media

- name: configure pirate
  hosts: pirate
  become: true
  tags: pirate
  roles:
    - docker/pirate
