---

- name: set facts and ssh user
  hosts: all
  become: no
  gather_facts: no
  ignore_errors: true
  ignore_unreachable: true
  roles:
  - global
  tags: always

# - name: install freeipa server
#   hosts: ipaserver
#   become: yes
#   tags: freeipa-server
#   roles:
#   - services/freeipa/server

- name: install & update packages
  hosts: all
  become: yes
  tags: install-update
  roles:
  - name: packages/install
  - name: packages/update
    tags: update

- name: register freeipa clients
  import_playbook: ../ansible-freeipa/playbooks/install-client.yml
  tags: freeipa-client

- name: configure servers group
  hosts: servers
  become: yes
  vars:
    sync: false # resets all configuration before re-applying
  tags: configure
  roles:
  - services/ssh/setup
  - name: services/collectd
    tags: collectd

- name: configure terminal
  hosts: all
  become: no
  tags: terminal
  roles:
  - terminal

- name: configure docker group
  hosts: docker
  become: yes
  tags: docker
  roles:
  - services/docker
  - name: docker/metrics
    when: not is_workstation

- name: configure kubernetes group
  hosts: kubernetes
  become: yes
  tags: kubernetes
  roles:
  - name: services/kubernetes
    vars:
      create_mnt_dirs: no
      dirs: []

- name: configure workstations group
  hosts: workstations
  tags: workstations
  roles:
  - workstations
  - name: docker/syncthing
    tags: docker/syncthing

- name: configure bastion
  hosts: bastion
  become: yes
  pre_tasks:
  - fail:
      msg: bastion host and duo settings required
    when: global.bastion is undefined or not global.bastion.host or not global.bastion.duo or not global.bastion.duo.ikey or not global.bastion.duo.skey or not global.bastion.duo.host
  tags: bastion
  roles:
  - services/duo
  - services/ssh/bastion
  - name: docker/sish
    tags: docker/sish

- name: configure guacamole
  hosts: guacamole
  become: yes
  tags: guacamole
  vars:
    initialize: false
  roles:
  - docker/guacamole

- name: configure postgresql
  hosts: postgres
  become: yes
  tags: postgresql
  vars:
    initialize: false
  roles:
  - docker/postgresql
