---

- name: configure spacewalk client
  hosts: spacewalkclients
  become: yes
  roles:
  - name: firewalld
    ports:
    - 22/tcp
    - 5222/tcp
    services: []
    when: ansible_os_family == "RedHat"
  - name: spacewalk-client
