---

- name: configure transmission
  hosts: transmission
  become: yes
  roles:
  - name: firewalld
    ports:
    - 51413/tcp
    - 51413/udp
    services:
    - http
    - https
  - name: transmission
    conf_mount: "{{ transmission_docker_path }}"
    downloads_mount: "{{ downloads_media_path }}"
