---

# use inventory that will not be registered with freeipa and spacewalk

- name: set facts and ssh user
  hosts: all
  become: no
  gather_facts: no
  ignore_errors: true
  ignore_unreachable: true
  roles:
  - global
  tags: always

- name: configure unowned servers
  become: yes
  hosts: all
  tags: configure
  pre_tasks:
  - fail:
      msg: target host should not be registered to freeipa
    when: is_freeipa
  roles:
  - name: packages/install
  - name: packages/update
    tags: update
  - name: services/ssh/setup
  - name: services/kubernetes
    vars:
      create_mnt_dirs: yes
      dirs:
      - /mnt/k8s/elasticsearch
      - /mnt/k8s/mongodb
      - /mnt/k8s/mysql
      - /mnt/k8s/postgresql
      - /mnt/k8s/rabbitmq
      - /mnt/k8s/redis

# - name: configure cluster
#   become: yes
#   import_playbook: ../kubespray/cluster.yml
#   tags: kubespray
