---

- name: create volumes
  docker_volume:
    name: "sonarr_{{ item.name }}"
    driver_options:
      type: nfs
      device: ":/{{ item.mount }}"
      o: "addr={{ nfs_host }},vers=4,tcp,rw,port=2049"
  with_items:
  - name: conf
    mount: "{{ conf_mount }}"
  - name: downloads
    mount: "{{ downloads_mount }}"
  - name: tv_shows
    mount: "{{ tv_shows_mount }}"

- name: start container
  docker_container:
    name: sonarr
    image: linuxserver/sonarr:latest
    restart_policy: unless-stopped
    env:
      TZ: America/Los_Angeles
      PUID: "{{ sonarr_docker_user_id | string }}"
      PGID: "0"
    ports:
    - 8989:8989
    volumes:
    - sonarr_conf:/config
    - sonarr_downloads:/downloads
    - sonarr_tv_shows:/tv
