---

- name: centos | open spacewalk server services
  include_role:
    name: services/firewalld/tasks
  vars:
    name: spacewalk server
    services:
    - name: spacewalk http
      service: http
    - name: spacewalk https
      service: https
    - name: spacewalk tftp
      service: tftp
    ports:
    - name: spacewalk monitoring
      port: 4545/tcp
    - name: spacewalk push actions
      port: 5222/tcp
