---

- name: install dependencies
  yum:
    name:
    - yum-plugin-tmprepo
    state: present

- name: service repo
  command: yum install -y spacewalk-repo --tmprepo=https://copr-be.cloud.fedoraproject.org/results/%40spacewalkproject/spacewalk-2.9/epel-7-x86_64/repodata/repomd.xml --nogpg

- name: epel dependency
  command: rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  ignore_errors: yes

- name: add answer file
  copy:
    content: |
      admin-email={{ spacewalk_admin_email }}
      ssl-set-cnames=spacewalk
      ssl-set-org=spacewalk
      ssl-set-org-unit=
      ssl-set-city=Los Angeles
      ssl-set-state=CA
      ssl-set-country=US
      ssl-password=
      ssl-set-email={{ spacewalk_admin_email }}
      ssl-config-sslvhost=Y
      db-backend=postgresql
      db-name={{ spacewalk_db_name }}
      db-user={{ spacewalk_db_user }}
      db-password={{ spacewalk_db_pass }}
      db-host={{ spacewalk_db_host }}
      db-port={{ spacewalk_db_port }}
      enable-tftp=Y
    dest: /tmp/answer

- name: install dependencies
  yum:
    name:
    - spacewalk-postgresql 
    - osa-dispatcher
    state: present
