- name: copy rootx1 crt
  copy:
    force: yes
    src: "rootx1.crt"
    dest: /etc/ssl/{{ certificate_common_name }}/{{ certificate_common_name }}.root.crt

- name: copy intermediate crt
  copy:
    force: yes
    src: "intermediate.crt"
    dest: /etc/ssl/{{ certificate_common_name }}/{{ certificate_common_name }}.intermediate.crt

- name: create file
  command: touch /etc/ssl/{{ certificate_common_name }}/{{ certificate_common_name }}.fullchain.pem

- name: concatenate full chain
  shell: cat /etc/ssl/{{ certificate_common_name }}/{{ certificate_common_name }}.crt /etc/ssl/{{ certificate_common_name }}/{{ certificate_common_name }}.intermediate.crt /etc/ssl/{{ certificate_common_name }}/{{ certificate_common_name }}.root.crt > /etc/ssl/{{ certificate_common_name }}/{{ certificate_common_name }}.fullchain.pem

- name: copy ca
  shell: cat /etc/ssl/{{ certificate_common_name }}/{{ certificate_common_name }}.intermediate.crt /etc/ssl/{{ certificate_common_name }}/{{ certificate_common_name }}.root.crt /etc/ipa/ca.crt
  when: is_freeipa

- name: pip | install cryptography
  become: false
  pip:
    name: cryptography
    state: latest

- name: create pk12
  openssl_pkcs12:
    action: export
    friendly_name: "{{ certificate_common_name }}"
    path: "/etc/ssl/{{ certificate_common_name }}/{{ certificate_common_name }}.pk12"
    privatekey_path: "/etc/ssl/{{ certificate_common_name }}/{{ certificate_common_name }}.key"
    certificate_path: "/etc/ssl/{{ certificate_common_name }}/{{ certificate_common_name }}.crt"
    other_certificates:
      - "/etc/ssl/{{ certificate_common_name }}/{{ certificate_common_name }}.intermediate.crt"
      - "/etc/ssl/{{ certificate_common_name }}/{{ certificate_common_name }}.root.crt"
    state: present
    passphrase: password
