---

- name: copy rootx1 crt
  copy:
    src: "rootx1.crt"
    dest: /etc/ssl/{{ certificate_common_name }}/{{ certificate_common_name }}.root

- name: create file
  command: touch /etc/ssl/{{ certificate_common_name }}/{{ certificate_common_name }}.fullchain

- name: concatenate full chain
  shell: cat /etc/ssl/{{ certificate_common_name }}/{{ certificate_common_name }}.crt /etc/ssl/{{ certificate_common_name }}/{{ certificate_common_name }}.intermediate.crt /etc/ssl/{{ certificate_common_name }}/{{ certificate_common_name }}.root > /etc/ssl/{{ certificate_common_name }}/{{ certificate_common_name }}.fullchain

- name: copy ca
  shell: cp /etc/ssl/{{ certificate_common_name }}/{{ certificate_common_name }}.intermediate.crt /etc/ipa/ca.crt
  when: is_freeipa_replica

- name: create pk12
  openssl_pkcs12:
    action: export
    friendly_name: "{{ certificate_common_name }}"
    path: "/etc/ssl/{{ certificate_common_name }}/{{ certificate_common_name }}.pk12"
    privatekey_path: "/etc/ssl/{{ certificate_common_name }}/{{ certificate_common_name }}.key"
    certificate_path: "/etc/ssl/{{ certificate_common_name }}/{{ certificate_common_name }}.crt"
    other_certificates:
    - "/etc/ssl/{{ certificate_common_name }}/{{ certificate_common_name }}.intermediate.crt"
    - "/etc/ssl/{{ certificate_common_name }}/{{ certificate_common_name }}.root"
    state: present
    passphrase: password
