---

- name: install pip dependencies
  become: no
  pip:
    name:
    - netaddr
    extra_args: --user
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: launch local docker containers
  import_tasks: docker/main.yaml

- name: bin | configure
  import_tasks: bin/main.yaml

- name: debian | configure
  import_tasks: debian/main.yaml
  when: is_debian

- name: centos | configure
  import_tasks: centos/main.yaml
  when: is_centos

- name: configure physical workstation
  import_tasks: physical/main.yaml
  when: is_physical_workstation

- name: configure vm workstation
  import_tasks: vm/main.yaml
  when: is_vm_workstation

- name: git | create global files
  copy:
    src: "files/{{ item }}"
    dest: "{{ ansible_env['HOME'] }}/{{ item }}"
  with_items:
  - .gitignore_global
  - .gittemplate_global

- name: git | create .gitconfig
  template:
    src: git.j2
    dest: "{{ ansible_env['HOME'] }}/.gitconfig"
    force: yes

- name: gcloud-sdk | create .gcloud dir
  file:
    path: "{{ ansible_env['HOME'] }}/.gcloud"
    state: directory
