- name: install apps in existing repo
  become: true
  apt:
    name:
      - slack-desktop
      - thunderbird
    state: latest

- name: install duck
  import_tasks: ../debian/generic.yaml
  vars:
    pkg_name: duck
    pkg_gpg_id: FE7097963FEFBE72
    pkg_gpg_keyserver: keyserver.ubuntu.com
    pkg_repository: deb https://s3.amazonaws.com/repo.deb.cyberduck.io stable main
    pkg_packages:
      - duck

# example deb url
# https://dl.cloudsmith.io/public/balena/etcher/config.deb.txt?distro=ubuntu&codename=xenial&version=20.10&arch=amd64
- name: install etcher
  import_tasks: ../debian/generic.yaml
  vars:
    pkg_name: etcher
    pkg_gpg_key: https://dl.cloudsmith.io/public/balena/etcher/gpg.70528471AFF9A051.key
    pkg_repository_name: etcher
    pkg_repository: deb https://dl.cloudsmith.io/public/balena/etcher/deb/ubuntu xenial main
    pkg_packages:
      - balena-etcher-electron

- name: install weechat
  import_tasks: ../debian/generic.yaml
  vars:
    pkg_name: weechat
    pkg_gpg_id: 11E9DE8848F2B65222AA75B8D1820DB22A11534E
    pkg_gpg_keyserver: keys.openpgp.org
    pkg_dependencies:
      - dirmngr
      - gnupg-agent
      - apt-transport-https
    pkg_packages:
      - screen
      - weechat-curses
      - weechat-plugins
      - weechat-python
      - weechat-perl

- name: install yq
  import_tasks: ../debian/generic.yaml
  vars:
    pkg_name: yq
    pkg_gpg_id: CC86BB64
    pkg_gpg_keyserver: keyserver.ubuntu.com
    pkg_repository: deb http://ppa.launchpad.net/rmescandon/yq/ubuntu focal main
    pkg_packages:
      - yq

- name: install spotify
  flatpak:
    name: com.spotify.Client
    state: latest

- name: install dbeaver ce
  flatpak:
    name: io.dbeaver.DBeaverCommunity
    state: latest
